Node bundle new
val-lang/val pull request #131
Opened 2022-12-01 15:11 UTC by lucteo

**Why?**
It is not straightforward to build logic after type-checking the Val program. The user needs to keep around a `TypedProgram` object and use it in parallel with walking over the AST. This creates a lot of boliderplate code

We want to remove the use of boilerplate code, and make the code that reasons on typed-checked node as easy as possible to reason about.

**How?**
- add *type-checked* nodes that reflect all the properties of the original nodes, but keeps the type information also around.
- allow clients to use `TypedXXX` to represent type-checked nodes

**Testing**
- all existing unit tests pass

2022-12-04 14:07 UTC, lucteo commented
attn: @dabrahams , @kyouko-taiga : Using inner enums in the AST nodes would require extra hoops if we translate them into typed nodes.

I'm not sure if there is a clean way to generate this automatically with key paths; @dabrahams do you know of a such a method?

2022-12-04 17:18 UTC, kyouko-taiga commented on Sources/Compiler/TypedChecked.swift
> +public protocol TypedChecked {}
I don't think his protocol is necessary. Having to maintain the list of type aliases is a heavy burden. I think it's better to use `TypedProgram.Node<T>` and rely on contextual type inference to reduce verbosity whenever possible.

Note that the aliases would have be duplicated if we want to have those augmented nodes for different phases of compilation (e.g., after scope construction, after borrow checking, ...)

2022-12-04 17:20 UTC, kyouko-taiga requested changes
Fantastic work! Most things look very good, except the TypedProtocol and its type aliases (see comments).

I wouldn't mind about testing. It's a cross-cutting feature that will get thoroughly tested indirectly.

2022-12-04 18:23 UTC, lucteo commented on Sources/Compiler/TypedChecked.swift
> +public protocol TypedChecked {}
This comes from @dabrahams 's suggestion on https://github.com/lucteo/val/commit/0debaebf1ca3844b0ec1ff3f5f3d3d7902769639#r91233054

I agree that it's not nice to duplicate the lists, but I feel it pays off in terms of readability. Do you know of any way that I can improve on the readability (i.e., don't add a lot of boilerplate code when mentioning typed nodes), and get rid of this ugly list?

2022-12-04 18:49 UTC, lucteo commented on Sources/Compiler/TypedChecked.swift
> +public protocol TypedChecked {}
Maybe, as a compromise between the two alternatives we can use something like: `typealias Typed<T: AST.Node> = SomeProgram.Node<T>`

Then, we we would use `Typed<FunctionDecl>` instead of `TypedFunctionDecl`. We would also do it from anywhere, not only from classes implemented `TypedChecked`.

How does that sound to you?

2022-12-04 22:50 UTC, dabrahams commented on Sources/Compiler/TypedChecked.swift
> +public protocol TypedChecked {}
Works for me!

2022-12-04 22:55 UTC, dabrahams commented on Sources/Compiler/TypedChecked.swift
> +public protocol TypedChecked {}
Aside from contextual type inference, for lines like:

```swift
return emit(returnStmt: TypedReturnStmt(stmt)!)
```

we have a prefix `^` operator convention that Dimi introduced.

```swift
return emit(returnStmt: (^stmt)!)
```

2022-12-05 21:26 UTC, lucteo commented on Sources/Compiler/TypedChecked.swift
> +public protocol TypedChecked {}
I'm now starting to remove `TypedChecked`...

Looking at the definition of `^`, I don't see how I can do what you mention above.
```
/// Creates a type-erased container wrapping the given instance.
public prefix func ^ <T: TypeProtocol>(_ base: T) -> AnyType {
  AnyType(base)
}
```

Besides this being specialized from the wrong type of protocol, I need the reverse of this operation.
For clarity, I would just use the full variant, i.e., `Typed<ReturnStmt>(stmt)!`

2022-12-05 21:46 UTC, lucteo commented on Sources/Compiler/TypedChecked.swift
> +public protocol TypedChecked {}
Patch is up.

Now I'm thinking of moving `TypedNode` (a typed node constructed from an ID) and `Typed` (constructed from an AST node) outside of `TypedProgram` (i.e., instead of `TypedProgram.SomeNode<>` and `TypedProgram.Node<>`. It will display better type names in the compiler, and will separate out the concerns a bit more (`TypedNode` would still depend on `TypedProgram`)

2022-12-08 12:45 UTC, kyouko-taiga commented on Sources/Compiler/AST/NodeIDs/NodeID.swift
> +  public init(_ source: Self) { self = source }
What is the purpose of this initializer? It seems its can only be used to create copies of `Self`.

2022-12-08 12:46 UTC, kyouko-taiga commented on Sources/Compiler/CXX/CXXModule.swift
> +    assert(program.isGlobal(valFunctionDecl.id))
_(non-blocking)_

I think it should be possible to implement `isGlobal` as a property of typed declarations.

2022-12-08 12:49 UTC, kyouko-taiga commented on Sources/Compiler/TypedNode.swift
> +extension AST {
```suggestion
public typealias ValNode = Node

extension AST {
```

2022-12-08 12:51 UTC, kyouko-taiga commented on Sources/Compiler/TypedNode.swift
> +}
```suggestion
public typealias ValNode = Node

extension AST {

  public typealias Node = ValNode
  
}
```

2022-12-08 12:51 UTC, kyouko-taiga commented on Sources/Compiler/TypedNode.swift
> +  /// The whole program of which this node is a notional part.
```suggestion
public struct TypedNode<ID: NodeIDProtocol> : Hashable {

  /// The whole program of which this node is a notional part.
```

2022-12-08 12:53 UTC, kyouko-taiga commented on Sources/Compiler/TypedNode.swift
> +  /// Hash function; only consider the node ID.
```suggestion
  /// Hashes `id` into `hasher`.
```

2022-12-08 12:54 UTC, kyouko-taiga commented on Sources/Compiler/TypedNode.swift
> +  /// Get the typed node for the given node ID.
```suggestion
  /// Bundles `id` together with `self`.
```

2022-12-08 12:55 UTC, kyouko-taiga commented on Sources/Compiler/TypedNode.swift
> +}
```suggestion
  var kind: NodeKind { id.kind }

}
```

2022-12-08 13:00 UTC, kyouko-taiga requested changes
I left a couple of comments.

Also, could you add a white space before and after the first and last declarations (respectively) in type declarations? For example:
```swift
// Good
struct Foo {

  /// Some comment.
  let x: Int

  /// Some comment.  
  let y: String

}

// Bad
struct Foo {
  /// Some comment.  
  let x: Int

  /// Some comment.  
  let y: String
}
```

2022-12-08 17:03 UTC, dabrahams commented on Sources/Compiler/AST/NodeIDs/NodeID.swift
> +  public init(_ source: Self) { self = source }
Probably a C++ instinct.  You don't need these in Swift; everything is implicitly copyable.

2022-12-10 21:24 UTC, lucteo commented on Sources/Compiler/CXX/CXXModule.swift
> +    assert(program.isGlobal(valFunctionDecl.id))
I would prefer to leave this out of this PR.

2022-12-10 21:27 UTC, lucteo commented
> Also, could you add a white space before and after the first and last declarations (respectively) in type declarations? For example:

I got so used to clang-format, that I can't no longer format the code without a formatting tool. I tried to find a similar thing in XCode but I didn't see it. Do you have an automatic formatter that you use?

2022-12-10 21:33 UTC, lucteo commented on Sources/Compiler/AST/NodeIDs/NodeID.swift
> +  public init(_ source: Self) { self = source }
If I remove this, the optional initializer below fails:
> Non-failable initializer requirement 'init(_:)' cannot be satisfied by a failable initializer ('init?')

2022-12-11 17:12 UTC, kyouko-taiga commented
Sadly I don't have good formatter to recommend. I think @dabrahams mentioned something about swift-format?

2022-12-11 17:14 UTC, kyouko-taiga approved these changes
LGTM. Let's not worry too much about code format. I'm sure things will eventually reached a fixed point.

2022-12-11 17:14 UTC, merged