Use indices and addresses to insert IR instructions
val-lang/val pull request #143
Opened 2022-12-11 18:07 UTC by kyouko-taiga

2022-12-14 18:00 UTC, dabrahams requested changes
Because you rebased while I was reviewing it, all my comments are marked outdated, and I have stopped reviewing so we have a chance of not losing my input.

2022-12-14 18:00 UTC, dabrahams commented on Sources/Compiler/IR/InstructionIndex.swift
> +  /// The index of the function in which the instruction resides.
```suggestion
  /// The function containing this position.
```

2022-12-14 18:00 UTC, dabrahams commented on Sources/Compiler/IR/InstructionIndex.swift
> +  /// The address of the block in which the instruction resides.
```suggestion
  /// The block containing this position.
```

2022-12-14 18:00 UTC, dabrahams commented on Sources/Compiler/IR/InstructionIndex.swift
> +  public let index: Block.Instructions.Index
```suggestion
  /// This position relative to its block.
  public let indexInBlock: Block.Instructions.Index
```

2022-12-14 18:00 UTC, dabrahams commented on Sources/Compiler/IR/InstructionIndex.swift
> +  /// Creates a path with the given properties.
In this context we don't know what "a path" means.  Please try again.

2022-12-14 18:00 UTC, dabrahams commented on Sources/Compiler/IR/InstructionID.swift
> +  /// Creates a path with the given properties.
In this context we don't know what "a path" means.  Please try again.

2022-12-14 18:00 UTC, dabrahams commented on Sources/Compiler/IR/Module.swift
> +  }
```suggestion
  /// Accesses the function at `i`.
  public subscript(_ i: Functions.Index) -> Function {
    _read { yield functions[i] }
    _modify { yield &functions[i] }
  }
```

or even, since function indices _are_ stable,

```suggestion
  /// Accesses the given function.
  public subscript(_ f: Functions.Index) -> Function {
    _read { yield functions[f] }
    _modify { yield &functions[f] }
  }
```

2022-12-14 18:00 UTC, dabrahams commented on Sources/Compiler/IR/Module.swift
> +  }
```suggestion
  /// Accesses the given block.
  public subscript(_ b: Block.ID) -> Block {
    _read   { yield  functions[b.function].blocks[b.address] }
    _modify { yield &functions[b.function].blocks[b.address] }
  }
```

Totally instinct question, and I'll accept a one-word answer: do we really want all of these subscripts to be public?

2022-12-14 18:00 UTC, dabrahams commented on Sources/Compiler/IR/Module.swift
> +  /// Accesses the instruction with the given identity.
See comments on the two subscripts above.

2022-12-14 18:02 UTC, kyouko-taiga commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> +      if block == module[function: functionID].blocks.firstAddress {
You can use subscript to access functions, blocks, and instructions. I want to make it explicit which kind of object you're accessing at the use site.

The rationale is the same as for overloaded visitors (e.g., `visit(functionCall)`).

2022-12-14 18:06 UTC, kyouko-taiga commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> -    with consumer: InstID,
In this particular case, I believe it makes sense to make the renaming part of the PR. There's a symmetry between `InstructionID` and `InstructionIndex` that is part of the suggested changes.

I think it's silly to create a new type and name it `InstIndex` only to push a PR right after to rename it.

2022-12-14 18:08 UTC, kyouko-taiga commented on Sources/Utils/DoublyLinkedList.swift
> +  /// "past the end" index to append `newElement` at the end of `self`.
Though it may be standard, it is not necessarily intuitive to everyone. It isn't for me and I always go back to `Array`'s documentation to remember how it should work.

2022-12-14 18:10 UTC, kyouko-taiga commented on Sources/Compiler/IR/InstructionID.swift
> +  /// The index of the function in which the instruction resides.
I prefer index here. `InstructionID` is not storing a function. Now that we have bundles, I think the distinction is relevant.

2022-12-14 18:11 UTC, kyouko-taiga commented on Sources/Compiler/IR/InstructionID.swift
> +  /// The address of the block in which the instruction resides.
The distinction is definitely relevant in for objects that could be either an address or an index.

2022-12-14 18:14 UTC, kyouko-taiga commented on Sources/Compiler/IR/InstructionID.swift
> +  public let address: Block.Instructions.Address
I know I am biased against multi-word identifiers because I really dislike came case, but somehow I feel this one is particularly unattractive.

2022-12-14 18:19 UTC, kyouko-taiga commented on Sources/Compiler/IR/InstructionID.swift
> +  public init(
Please don't assume I'm never considering use sites ;)
I did hear, and I thought the labels helped.

I'm not opposed to remove them but I'm not a fan of having an initial `path:`.

2022-12-14 18:21 UTC, kyouko-taiga commented on Sources/Compiler/IR/InstructionIndex.swift
> +/// An index denoting an instruction in a module.
I think we should own the fact that in Swift "index" and "position" are interchangeable terms. Given that observation, I'd be tempted to use "index" in the documentation because that's the name of `Collection`'s associated type.

2022-12-14 18:23 UTC, kyouko-taiga commented on Sources/Compiler/IR/Module.swift
> +  }
As mentioned earlier, I want to keep the label.

2022-12-14 18:23 UTC, kyouko-taiga commented on Sources/Compiler/IR/Module.swift
> +  }
yes

2022-12-14 18:24 UTC, dabrahams commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> +      if block == module[function: functionID].blocks.firstAddress {
> I want to make it explicit which kind of object you're accessing at the use site.

Why?  Look at the use site; isn't it obvious that it's not helping?

> The rationale is the same as for overloaded visitors (e.g., visit(functionCall:)).

I disagree that it's the same at all.  The visitor functions typically have tens of overloads which makes finding the one you want difficult.  These subscripts don't have that problem.

2022-12-14 18:26 UTC, dabrahams commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> -    with consumer: InstID,
🤷 Doing a good PR review is a lot of work.  I'd rather be writing code.  It isn't silly at all to group renames that don't otherwise change functionality or API separately if it helps reviewers.

2022-12-14 18:26 UTC, kyouko-taiga commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> +      if block == module[function: functionID].blocks.firstAddress {
It's obvious in this particular call site because the index is called `functionID`. This call site would not be that obvious:

```swift
module[continuation].inputs
```

Basic blocks and functions have inputs. `continuation` is a reasonable name for either of these entities..

2022-12-14 18:27 UTC, dabrahams commented on Sources/Utils/DoublyLinkedList.swift
> +  /// "past the end" index to append `newElement` at the end of `self`.
🤷 Anything you can name is "not necessarily intuitive to everyone."  If we go out of our way to explain how every common idiom works every time we use it, we're making the code harder to read, not easier.

2022-12-14 18:29 UTC, dabrahams commented on Sources/Compiler/IR/InstructionID.swift
> +  /// The address of the block in which the instruction resides.
The distinction is there in the type.  Documentation should explain semantic value at the level of the abstraction being defined.

2022-12-14 18:30 UTC, dabrahams commented on Sources/Compiler/IR/InstructionID.swift
> +  /// The index of the function in which the instruction resides.
The distinction is there in the type. Documentation should explain semantic value at the level of the abstraction being defined.

2022-12-14 18:30 UTC, dabrahams commented on Sources/Compiler/IR/InstructionID.swift
> +  public let address: Block.Instructions.Address
Yes, I don't like the aesthetics either.   By all means come up with something prettier.  But semantics outweigh aesthetics.

2022-12-14 18:33 UTC, dabrahams commented on Sources/Compiler/IR/InstructionIndex.swift
> +/// An index denoting an instruction in a module.
> I think we should own the fact that in Swift "index" and "position" are interchangeable terms.

I do own it.  It's marginally helpful to use a different word even if the two words are normally interchangeable.  That's especially true because "index" has other valid meanings.

2022-12-14 18:33 UTC, kyouko-taiga commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> -    with consumer: InstID,
If I commit a new type named `InstIndex` *after* having merged your "de-abbrev `Inst`" PR, I can almost predict you'll comment:

> Didn't we agree we should not abbreviate "Inst"?

2022-12-14 18:34 UTC, dabrahams commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> -    with consumer: InstID,
What's your point?

2022-12-14 18:35 UTC, kyouko-taiga commented on Sources/Utils/DoublyLinkedList.swift
> +  /// "past the end" index to append `newElement` at the end of `self`.
Let's agree that if it helps one of the main maintainer of the code be more efficient, then it's worth it ;)

2022-12-14 18:37 UTC, kyouko-taiga commented on Sources/Compiler/IR/InstructionIndex.swift
> +/// An index denoting an instruction in a module.
My point is that these other meanings are mostly relevant outside of the Swift ecosystem.

2022-12-14 18:40 UTC, dabrahams commented on Sources/Utils/DoublyLinkedList.swift
> +  /// "past the end" index to append `newElement` at the end of `self`.
OK. Do you want me to explain this any time I write an insertion API using an index to denote position?  Just LMK.

2022-12-14 18:42 UTC, kyouko-taiga commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> -    with consumer: InstID,
It's a catch-22. Either I rename `InstID` and you need to stumble upon seemingly unrelated renames, or I define `InstIndex` and prompts you to request a name change.

Let's put it this way. The relationship between `InstructionID` and `InstructionIndex` is significant. It stems from the observations hat both concepts are necessary. The names of these types highlight the relationship. `InstID` would be semantically farther to `InstrunctionIndex` than `InstructionID` is. To me, it follows that I'm justified renaming `InstID` in this PR.

2022-12-14 18:45 UTC, dabrahams commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> +      if block == module[function: functionID].blocks.firstAddress {
In that code, you know you're getting the continuation out of the module and looking at its inputs. It absolutely doesn't matter whether it's a basic block or a function.  I object to putting type indications into non-type names because the idea that you need to do it basically implies reading generic programs is impossible.

2022-12-14 18:46 UTC, dabrahams commented on Sources/Compiler/IR/InstructionIndex.swift
> +/// An index denoting an instruction in a module.
I don't understand why that matters.  I did say "marginally."

2022-12-14 18:49 UTC, kyouko-taiga commented on Sources/Utils/DoublyLinkedList.swift
> +  /// "past the end" index to append `newElement` at the end of `self`.
That will certainly be helpful to me.

2022-12-14 18:53 UTC, kyouko-taiga commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> +      if block == module[function: functionID].blocks.firstAddress {
I am surprised you're fighting against this so strongly. This is a form of type-based overloading, one of which we wanted to get rid of. The only way for the reader to infer what the type of `module[continuation].inputs` is is to know the different overloads of `module.[]`and the type of `continuation`.

It's fine though, I won't die on that hill. Let's remove the labels.

2022-12-14 19:25 UTC, kyouko-taiga commented on Sources/Compiler/IR/InstructionIndex.swift
> +/// An index denoting an instruction in a module.
I think the use of the term "position" is confusing, because it suggests the existence of another kind of abstraction, different from an index. I guess the ship has sailed because we already use "position" and "index" interchangeably in many places of the code, but I believe it was a mistake.

Given the situation, however, I'm fine with your suggested edit. I'm sure the discussion about "position" and "index" will come back when we document Val's standard library.

2022-12-14 19:29 UTC, kyouko-taiga commented on Sources/Compiler/IR/InstructionID.swift
> +  public let address: Block.Instructions.Address
I have another idea. I'll propose it is a different PR.

2022-12-14 21:04 UTC, dabrahams commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> -    with consumer: InstID,
I'm sorry, I don't understand. I got lost, which probably means I don't understand the situation as well as I thought. So I withdraw the comment.

2022-12-14 21:13 UTC, dabrahams commented
> On Dec 14, 2022, at 10:53 AM, Dimi Racordon ***@***.***> wrote:
> 
> I am surprised you're fighting against this so strongly. This is a form of type-based overloading, one of which we wanted to get rid of.

Until we finally relented.

I understand why it’s confusing to you, but there actually is a logic behind what I’m saying.  I’d rather not have type-based overloads because it hurts code writers.  However, readers take precedence over writers, and when the overloads form a logical unit (this particular unit could have been a single subscript that is generic over `T: ModuleComponentID` for example) it’s better to group the names rather than to inject type information at the use-site.

> The only way for the reader to infer what the type of module[continuation].inputs is is to know the different overloads of module.[]and the type of continuation.

Knowing the type is not that important.  You can understand the semantics of that statement without knowing its type: it gets you the inputs of the continuation.  I strongly believe that adding words to API just to describe the types of (sub) expressions is more harmful than helpful, as a rule.

2022-12-15 00:54 UTC, dabrahams approved these changes
Please see inline comments.  Some of these things may be English subtleties, but I think it's more about speaking in terms of the abstractions the reader is using.  Let me know if you have questions!

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
>    public mutating func run(function functionID: Function.ID, module: inout Module) -> Bool {
Missing a doc

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
>    /// Creates the before-context of the function's entry block.
```suggestion
  /// Returns the before-context of the function's entry block.
```

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
>    private mutating func eval(block: Function.Blocks.Address, in module: inout Module) -> Bool {
Because of the missing doc here, it's hard to evaluate what is going on. The function signature _reads_ like this is part of an interpreter implementation.

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> +    let alloc = module[instruction.location.instruction!] as! AllocStackInstruction
it's hard to guess what `instruction.location.instruction!` might mean.  The whole line reads as a pile of types, suggesting there might be better names for these things.  But, hard to know with no doc.  Can you use role-based naming?

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> +        module[id.function][id.block].instructions.address(before: id.address)!)
There ought to be a more expressive way to say this.  Something like

```swift
let consumer = id.prior(in: module)
```

or something?  It would be much clearer with a role-based name for `id`.

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/Analysis/DominatorTree.swift
> +    let function = module[functionID]
```suggestion
    let subject = module[functionID]
```

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/Analysis/DominatorTree.swift
> +      for i in module[definition.function][definition.block].instructions.indices {
If we're doing stuff like this a lot, maybe we should have `module[blockOf: definition]` or something.

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/InstructionID.swift
> +  /// The function containing this identity.
```suggestion
  /// The function containing the instruction.
```

or if you must,

```suggestion
  /// The function containing the identified instruction.
```

What you wrote here suggests that you can query the function and find this identity stored therein.

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/InstructionID.swift
> +  /// The block containing this identity.
```suggestion
  /// The block containing the instruction.
```

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/InstructionID.swift
> +  /// The identity of the instruction in its block.
"the instruction" works fine here; why not above?

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/InstructionID.swift
> +  /// Creates an identity with the given properties.
```suggestion
  /// Creates an instance with the given properties.
```
“creates an identity” makes me think it's doing more than just creating an instance of this type, and I wonder what else is going on.  When I see "Creates an instance” I am able to skip over it as the standard phrase for “makes one of these.”  Does that make sense?

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/InstructionID.swift
> +  /// Creates an identity with the given properties.
```suggestion
  /// Creates an instance with the given properties.
```

But I don't think this comment is accurate; it has no property of type `Block.ID`.

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/InstructionIndex.swift
> +  /// The function containing this index.
same problem.  A thing doesn't contain its own indices, in general.

```suggestion
  /// The function in the module where this position is located.
```
or

```suggestion
  /// The function part of this position.
```

Or even,

```suggestion
  /// The function containing this position.
```

It's subtle, but this is the difference between the abstraction “position” and “index,” which indicates a datum.  The former works in that context, but the latter does not.

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/InstructionIndex.swift
> +  /// The block containing this index.
```suggestion
  /// The block in the module where this position is located.
```
or

```suggestion
  /// The function part of this position.
```

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/InstructionIndex.swift
> +  public init(_ block: Block.ID, _ index: Block.Instructions.Index) {
comment is not quite accurate, as per similar remark above.

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/Module.swift
> +    at position: InstructionIndex
```suggestion
    at insertionPoint: InstructionIndex
```

role-based naming

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/Module.swift
> +    before id: InstructionID
```suggestion
    before successor: InstructionID
```

role-based naming

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/Module.swift
> +    after id: InstructionID
```suggestion
    after predecessor: InstructionID
```

role-based naming

2022-12-15 00:54 UTC, dabrahams commented on Sources/Compiler/IR/Operands/Instruction/CallInstruction.swift
> +          if let instruction = module[id] as? BorrowInstruction {
Arguably `guard` can help readability in these situations by reducing nesting (also below).

2022-12-15 00:59 UTC, kyouko-taiga commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
>    public mutating func run(function functionID: Function.ID, module: inout Module) -> Bool {
The doc is inherited from the protocol to which the pass conforms.

2022-12-15 01:00 UTC, kyouko-taiga commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
>    private mutating func eval(block: Function.Blocks.Address, in module: inout Module) -> Bool {
That's because this pass is an interpreter ;)

2022-12-15 01:03 UTC, kyouko-taiga commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> +    let alloc = module[instruction.location.instruction!] as! AllocStackInstruction
The first `instruction` is the name of function parameter. I guess we could rename it to `deallocStack`. `location` is the role of the property. The second `instruction` is an application of your pattern fro extracting payload out of enums.

2022-12-15 01:04 UTC, kyouko-taiga commented on Sources/Compiler/IR/Analysis/DefiniteInitializationPass.swift
> +        module[id.function][id.block].instructions.address(before: id.address)!)
Sounds like a good idea. Can you open a issue?

2022-12-15 01:07 UTC, kyouko-taiga commented on Sources/Compiler/IR/InstructionID.swift
> +  /// Creates an identity with the given properties.
`Block.ID` is just a bundle for the properties. I think that is fine. I really want a way to document member wise-like initializers without ceremony.

2022-12-15 01:18 UTC, kyouko-taiga commented on Sources/Compiler/IR/Operands/Instruction/CallInstruction.swift
> +          if let instruction = module[id] as? BorrowInstruction {
`guard` failed me more than I can count during debugging. We're not on good terms anymore.

2022-12-15 20:05 UTC, merged