Apply swift-format
val-lang/val pull request #145
Opened 2022-12-11 21:02 UTC by dabrahams

I ran it with the default settings:

```sh
swift-format -i -r -p Sources Tests *.swift
```

I think the results are mostly reasonable.  What do y'all think?

2022-12-12 17:03 UTC, kyouko-taiga requested changes
It seems to work well for argument lists and fix a handful of small issues here and there, but I strongly disagree with the vertical space rules.

2022-12-12 22:52 UTC, dabrahams commented on Sources/Compiler/AST/AST.swift
> +        for i in 0..<self[p].elements.count {
Seriously?  If we had a tool that could eliminate formatting concerns except for this, you'd reject it?

2022-12-12 22:52 UTC, dabrahams commented
@kyouko-taiga which vertical space rules?

2022-12-12 23:04 UTC, kyouko-taiga commented on Sources/Compiler/AST/AST.swift
> +        for i in 0..<self[p].elements.count {
Probably, or I'd end up regularly going over all occurrences of the range operators and manually reinsert spaces.

2022-12-12 23:09 UTC, kyouko-taiga commented
Sorry, I meant horizontal.

I think it should be possible to write this for example:
https://github.com/val-lang/val/blob/99d275fb287861f451a0c1f3b5c93cf577d8f3f6/Sources/Compiler/CXX/CXXIdentifier.swift#L20-L31

Ideally, but less importantly, I think it should be possible to align statements after switch cases:
https://github.com/val-lang/val/blob/99d275fb287861f451a0c1f3b5c93cf577d8f3f6/Sources/Compiler/AST/Decl/Implntroducer.swift#L13-L19

2022-12-12 23:22 UTC, dabrahams commented
> On Dec 12, 2022, at 3:09 PM, Dimi Racordon ***@***.***> wrote:
> 
> I think it should be possible to write this for example:
> https://github.com/val-lang/val/blob/99d275fb287861f451a0c1f3b5c93cf577d8f3f6/Sources/Compiler/CXX/CXXIdentifier.swift#L20-L31
> 
That particular thing just creates busywork whenever the list changes; there’s no logical association between the things that are horizontally aligned.. 
> Ideally, but less importantly, I think it should be possible to align statements after switch cases:
> https://github.com/val-lang/val/blob/99d275fb287861f451a0c1f3b5c93cf577d8f3f6/Sources/Compiler/AST/Decl/Implntroducer.swift#L13-L19
> 

That’s another abuse of meaningless horizontal alignment, IMO, and again just creates busywork.

Although I disagree with you about when horizontal alignment should be used, it _is_ possible to write such things, though: see this <https://github.com/apple/swift-format/blob/main/Documentation/IgnoringSource.md>.

2022-12-12 23:23 UTC, kyouko-taiga commented on Sources/Compiler/AST/AST.swift
> +        for i in 0..<self[p].elements.count {
`..<` and `...` are infix operators, just like `+` and `-`. I think it really helps to put spaces around infix operators to distinguish them from prefix/postfix operators.

It's important to me because of consistency and because I find using infix operators without any spaces makes expressions harder to parse for my eyes.

"Over my dead body" might be a little strong, but I do really care.

2022-12-12 23:26 UTC, kyouko-taiga commented
OK for the array of strings, but I genuinely think aligning one-liners in switch-statements helps.

2022-12-12 23:31 UTC, dabrahams commented on Sources/Compiler/AST/AST.swift
> +        for i in 0..<self[p].elements.count {
I understand the consistency argument, and that it's easier for _you_, but consider that other people have to read the code and _everywhere_ else in the world those operators are used without spaces.  Again, I don't mind the spaces, but overall, this is going to make the code less familiar to people.  If I was doing the calculation for the good of the whole project, I'd remove them.  

But regardless, it's possible to make swift format put those spaces in with a tiny bit o' work.

2022-12-13 01:01 UTC, dabrahams commented on Sources/Compiler/AST/AST.swift
> +        for i in 0..<self[p].elements.count {
et [voilà](https://github.com/apple/swift-format/pull/459).

2022-12-13 01:19 UTC, kyouko-taiga commented on Sources/Compiler/AST/AST.swift
> +        for i in 0..<self[p].elements.count {
Thank you ❤️

2022-12-13 03:27 UTC, dabrahams commented
> OK for the array of strings, but I genuinely think aligning one-liners in switch-statements helps.

OK, I went through and added `// swift-format-ignore` to those switch statements.  I have to say, however much you think it helps readability, it's going to act as a disincentive to contribution.  I'm afraid to touch a switch statement now.

2022-12-13 03:51 UTC, dabrahams commented
I'm not fond of [this change](https://github.com/val-lang/val/pull/145/files#diff-3ce729fe5445a28a6dfd9ec83fe0c3c7994ccecf56e1e78c1f584a9398c95533L234-L242), but the way it turned out is due in part to the fact that there are existing line breaks and we have `"respectsExistingLineBreaks" : true`.

2022-12-13 13:35 UTC, kyouko-taiga approved these changes
I really don't understand why it's important to be strict about the horizontal indentation in switch statements (e.g., [here](https://github.com/val-lang/val/pull/145/files#diff-3b350835f885ab0b7e932b4406a686d196d34d0de63f2018e69f3ca0d95b1183R225-R230)), conditions (e.g., [here](https://github.com/val-lang/val/pull/145/files#diff-14c55d7cc99badd925ef82566064a3871ed7d08ddb518a90c090c00588674625R147-R148)), infix expressions, or comments (e.g., [here](https://github.com/val-lang/val/pull/145/files#diff-a48964fcac18bfe0938dbc8d6031fd98318d3f1fc41d7c70ae851175fc693b6eR390-R393)). I think the main point of the 2 spaces indentation is to identify scopes and that developers should have freedom to decide how they want to write long expressions.

I'm also sure you can appreciate that it is a little frustrating to have to change the way I code after roughly 70K LoC only to appease a linter. But I understand it will be helpful to have an automated arbiter so that's all good. You can also remove the aforementioned `swift-format-ignore` if you think that discourages contributions.

2022-12-13 15:56 UTC, dabrahams commented
> On Dec 13, 2022, at 5:35 AM, Dimi Racordon ***@***.***> wrote:
> 
> I really don't understand why it's important to be strict about the horizontal indentation in switch statements (e.g., here <https://github.com/val-lang/val/pull/145/files#diff-3b350835f885ab0b7e932b4406a686d196d34d0de63f2018e69f3ca0d95b1183R225-R230>), conditions (e.g., here <https://github.com/val-lang/val/pull/145/files#diff-14c55d7cc99badd925ef82566064a3871ed7d08ddb518a90c090c00588674625R147-R148>), infix expressions, or comments (e.g., here <https://github.com/val-lang/val/pull/145/files#diff-a48964fcac18bfe0938dbc8d6031fd98318d3f1fc41d7c70ae851175fc693b6eR390-R393>). I think the main point of the 2 spaces indentation is to identify scopes and that developers should have freedom to decide how they want to write long expressions.
> 
I agree with you about most of these.  This is an experiment to see if we can live with it.  Even if we loved all the results (and I don’t) there remain questions about how it would be integrated into our workflows.
> I'm also sure you can appreciate that it is a little frustrating to have to change the way I code after roughly 70K LoC only to appease a linter.
> 
Well now, you don’t have to do anything.
> But I understand it will be helpful to have an automated arbiter so that's all good. You can also remove the aforementioned swift-format-ignore if you think that discourages contributions.
> 

The swift-format-ignore is not the problem of course.  It's horizontal alignment across lines that discourages contributors, which is only mitigated when you have a formatting tool that can put it in for them.  But we don’t have one.

2022-12-13 21:06 UTC, dabrahams commented
@lucteo This is ready for you to merge as soon as CI is done with it.

2022-12-13 21:16 UTC, dabrahams commented
Tested in release mode locally; merging now to unblock progress.

2022-12-13 21:16 UTC, merged