Refactor constraint generation
val-lang/val pull request #177
Opened 2022-12-20 01:25 UTC by kyouko-taiga

2022-12-20 16:44 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +    let didFoundError: Bool
```suggestion
    let foundError: Bool
```
Although the above name is slightly ambiguous; it could be the error that was found.

```suggestion
    let errorFound: Bool
```

doesn't have that problem.

This is the old Cocoa style which seems pointless to me.
```suggestion
    let didFindError: Bool
```

2022-12-20 16:47 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +    /// Indicates that the solver encountered one or more errors.
And how does it indicate that? By being present?  By being `false`? ;-)

```suggestion
    /// True iff the solver encountered an error.
```

or if you must,

```suggestion
    /// True iff the solver encountered one or more errors.
```

or if you *truly* must

```suggestion
    /// Whether the solver encountered one or more errors.
```

2022-12-20 16:49 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +    /// Indicates that the solver encountered one or more errors.
You don't tell me what "error" means in this context.  Without qualification, in programming, "error" usually means "postcondition failure" but I'm guessing this error is something more like a contradiction.  Why not use a more specific word?

2022-12-20 17:46 UTC, dabrahams requested changes
A few things need to be cleaned up.

2022-12-20 17:46 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +    assumeIsError(id)
I realize this is an idiom throughout and not introduced by this PR, but I don't know what "assume" means in this context.

2022-12-20 17:46 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +    assume(
`assume` is undocumented so I can't evaluate its use sites.  However, I find it "weird to be saying assume <some AST node> is <some type>."  I know we use `x is T` at the language level, but I'd rather read `hasType` here (and maybe in the language too) because `is` can mean equality

2022-12-20 17:46 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> -    case MapLiteralExpr.self:
Just curious as to what caused all these deletions.

2022-12-20 17:46 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +      at: checker.program.ast[id].origin)
Couldn't assume get the origin from its first parameter?  Presumably the ConstraintGenerator could store the program directly?

2022-12-20 17:46 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
>        let parameters = visit(arguments: checker.program.ast[id].arguments, using: &checker)
Are these parameters or arguments?  The code here makes it unclear that you know which you're dealing with.

2022-12-20 17:46 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +          calleeType, takes: parameters, andReturns: returnType,
I bet this is a constraint that the calleeType can accept _arguments_ of the given type… ?  I would use `canAccept` or something to indicate that these are not necessarily the types of the parameters (unless I'm confused)

2022-12-20 17:46 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +      return assumeIsError(id)
That function is undocumented so can't evaluate.

2022-12-20 17:46 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +      assert(!prefix.isEmpty)
It's always nice to add some descriptive string to an assert about what expectation is being violated, embedding some information there, so when it fires, the person who has to deal with it has a clue.

2022-12-20 17:46 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +        parentType = constrain(p.component, to: p.candidates, using: &checker)
It seems odd that you're willing to overwrite `parentType` each time through the loop. Is this really correct?

2022-12-20 17:46 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/TypeChecker.swift
> +    case failed
No payload; the comment is out of date.

2022-12-20 19:19 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/TypeChecker.swift
> +  /// with the solution describing the best guess for its type and that of its sub-expressions.
No, because if inference failed I still want its best solution; it likely contains diagnostics that I can report to explain the failure.

2022-12-20 19:23 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/TypeChecker.swift
Are you talking about [`TypeChecker.infer(typeOf:expecting:inScope:initialConstraints:)`](https://github.com/val-lang/val/blob/bd6c1a5ba71a7f749980276f0691b7b5ca68a614/Sources/FrontEnd/TypeChecking/TypeChecker.swift#L1483) (L1483)?

The function returns two things (return type is `(succeeded: Bool, solution: Solution)`).
The comment says "Returns whether [...] along with [...]."

2022-12-20 19:25 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/TypeChecker.swift
Not the previous function, the [following one](https://github.com/val-lang/val/blob/bd6c1a5ba71a7f749980276f0691b7b5ca68a614/Sources/FrontEnd/TypeChecking/TypeChecker.swift#L1523-L1530).

2022-12-20 19:32 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
>    mutating func apply(using checker: inout TypeChecker) -> Result {
I'm hinting at the fact that `self` is notionally a function (its initializer can be understood as building the capture list). So I used "applies" to mean "applies the notional function represented by `self`". Would that be a better comment? Do you have another suggestion?

FWIW, I have some insider information that methods of the `ConstraintGenerator` will migrate to an extension of `TypeChecker` very soon.

2022-12-20 19:37 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +      if !checker.check(brace: thenBlock) { didFoundError = true }
Really?

`brace` is for `NodeID<BraceStmt>`, which is what the "then" block of a conditional statement is. I'm open to suggestions.

2022-12-20 19:39 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +    assume(
Sounds good.

As for the language level, it's a good discussion to open. Note that Val currently doesn't have an `is` operator.

2022-12-20 19:52 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> -    case MapLiteralExpr.self:
There were dead artifacts of the time the constraint generator used to be an AST visitor.

2022-12-20 19:52 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +      at: checker.program.ast[id].origin)
Yes, that's in the pipes for a future patch.

2022-12-20 19:55 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
>        let parameters = visit(arguments: checker.program.ast[id].arguments, using: &checker)
All of these variables are properly named. We're guessing the type of the parameters from the bottom-up information that we can gather from the arguments. The docs of `visit(arguments:using:)` is explaining the same thing.

I'm open to suggestions if more is needed at the call site.

2022-12-20 20:05 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
>    mutating func apply(using checker: inout TypeChecker) -> Result {
I'd just say "Returns the constraints for _______ using `checker` to resolve…”
This notional function business is info the reader doesn't need at this point.

2022-12-20 20:06 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +        parentType = constrain(p.component, to: p.candidates, using: &checker)
Yes, this is the parent type of the last visited component.

2022-12-20 20:06 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +      if !checker.check(brace: thenBlock) { didFoundError = true }
Terrible label then!  It's not a single brace, but a BraceStmt.

2022-12-20 20:08 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
>        let parameters = visit(arguments: checker.program.ast[id].arguments, using: &checker)
Part of the problem here is that `visit` is a huge missed opportunity to communicate something about what it does.

2022-12-20 20:14 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +      if !checker.check(brace: thenBlock) { didFoundError = true }
Noted ;)

All `check` methods are labeled `blah` for `BlahStmt`, so that just follows the pattern. Let's revisit this choice in another patch.

2022-12-21 19:08 UTC, dabrahams approved these changes
Approving, but it looks like some of my earlier remarks were ignored.

2022-12-21 19:08 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +          calleeType, takes: parameters, andReturns: returnType,
OK, if I was confused, then the constraint is misnamed and what you really have here is a `FunctionTypeConstraint`.  And I would replace `takes` with `parameters` in this case, just to avoid confusion about whether you're documenting the types it can accept or its concrete argument types.

2022-12-21 19:08 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +      checker.addDiagnostic(
You probably can't do anything about it in this PR, but I'd rather be reading

```swift
checker.diagnose(labels: argumentLabels, incompatibleWith: parameterLabels)
```

2022-12-21 19:08 UTC, dabrahams commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +  private var didFoundError = false
Still ungrammatical and the documentation style is at least not like what we do everywhere else

2022-12-21 23:52 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +  /// Returns the variable assigned to `expr` in the generated contraints, using `checker` to
Sorry, I missed that there were two occurrences of `didFoundError`. I replaced by
```swift
/// True iff a constraint could not be solved.
  private var foundConflict = false
```

2022-12-21 23:57 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +    let didFoundError: Bool
Sorry, I missed that there were two occurrences of properties with this name. I replaced (now instances) by:
```swift
/// True iff a constraint could not be solved.
let foundConflict: Bool
```

2022-12-22 00:01 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +    /// Indicates that the solver encountered one or more errors.
The property is no called `foundConflict` and the docs don't mention "errors" anymore.

I have to say, though, that it think it's reasonable to use the term "error" in the source code of a type checker to mean something else than a programming error of the type checker itself. I would not expect a component named "TypeChecker" or "ConstraintSolver" to set a flag when it encounters an error in its own implementation.

2022-12-22 00:06 UTC, kyouko-taiga commented on Sources/FrontEnd/TypeChecking/ConstraintGenerator.swift
> +          calleeType, takes: parameters, andReturns: returnType,
I'm afraid I didn't fully understand your comment. Please open an issue if you want to fix this in another patch.

2022-12-22 00:07 UTC, merged

2022-12-22 01:25 UTC, dabrahams commented
> On Dec 21, 2022, at 4:01 PM, Dimi Racordon ***@***.***> wrote:
> 
> 
> @kyouko-taiga commented on this pull request.
> 
> I have to say, though, that it think it's reasonable to use the term "error" in the source code of a type checker to mean something else than a programming error of the type checker itself.
> 
Of course it is, but without qualification it could still mean one of several things, e.g. an inconsistency in a particular constraint resolution path or a hard error that needs to be reported to the user.
> I would not expect a component named "TypeChecker" or "ConstraintSolver" to set a flag when it encounters an error in its own implementation.
> 
That's a “bug,” (usually precondition violation) which I never classify as an “error."  In Swift, an error is a response to a recoverable postcondition failure; it’s the thing that gets thrown.