Use typed nodes in the IR code
val-lang/val pull request #193
Opened 2022-12-31 13:14 UTC by lucteo

IR code used in a few occasions untyped nodes. Use typed nodes instead.

This is a continuation of the effort to use typed nodes instead of pairing AST nodes with TypedProgram.

2023-01-04 10:15 UTC, kyouko-taiga commented on Sources/Core/TypedNode.swift
> +  /// In most cases, the type is valid, so we extract the value from the optional by default.
I feel like this comment should be an implementation note in the body of this accessor.

2023-01-04 10:16 UTC, kyouko-taiga commented on Sources/Core/TypedNode.swift
>      program.declTypes[id]!
If we do as below, we don't need forced unwrapping anymore and we can represent failures to type check an expression with the error type.

```suggestion
    program.declTypes[id] ?? .error
```

2023-01-04 10:18 UTC, kyouko-taiga requested changes
Good work.

I think we can avoid exposing the type of a typed expression node as an optional.

2023-01-05 11:19 UTC, lucteo commented on Sources/Core/TypedNode.swift
>      program.declTypes[id]!
Makes a lot of sense. Will fix.

2023-01-05 14:02 UTC, kyouko-taiga approved these changes
LGTM

2023-01-05 19:08 UTC, merged