Pretty print JSON, add type names.
val-lang/val pull request #223
Opened 2023-01-11 12:43 UTC by oskidan

Hi everyone, :wave:

Hopefully this PR makes the generated JSON a bit more readable.

Resolves: #70

2023-01-17 09:37 UTC, kyouko-taiga commented on Sources/Core/AST/AnyNode.swift
> +    try container.encode("\(nodeType)", forKey: .nodeName)
```suggestion
    let nodeType = type(of: node)
    try container.encode("\(type(of: node))", forKey: .nodeName)
```

2023-01-17 09:37 UTC, kyouko-taiga commented on Sources/Core/AST/AnyNode.swift
> +    case nodeName, kind, data
```suggestion
    case nodeType, kind, data
```

2023-01-17 09:39 UTC, kyouko-taiga commented on Sources/Core/AST/AnyNode.swift
> +    case nodeName, kind, data
```suggestion
    case nodeType, kind, data
```

2023-01-17 09:41 UTC, kyouko-taiga requested changes
Thanks for this contribution!

I think `CodingKeys.nodeName` should be renamed `CodingKeys.nodeType`. Except that, I the changes should make json outputs more usable. Good job.

2023-01-17 20:51 UTC, oskidan commented on Sources/Core/AST/AnyNode.swift
> +    case nodeName, kind, data
Makes sense. Done.

2023-01-18 08:52 UTC, kyouko-taiga approved these changes
LGTM

2023-01-20 21:45 UTC, dabrahams requested changes
Sorry, I can't tell what this accomplishes by looking at the code.  I'd like to see a test added that would fail before these changes and passes afterward.  Thanks!

2023-02-24 07:05 UTC, C-BJ commented
What's wrong with this PR? @kyouko-taiga

2023-02-24 14:50 UTC, kyouko-taiga commented
Dave asked for a test that would highlight what the PR is accomplishing.

2023-08-10 11:27 UTC, kyouko-taiga commented
I think this PR has gone stale.

There's a related issue on the topic of visualizing ASTs (see #70).

2023-08-10 11:27 UTC, closed without merging