Make most Source ranges non-optional.
val-lang/val pull request #241
Opened 2023-01-19 20:16 UTC by dabrahams

(IR instructions are a separate issue.)

Addresses #239

There will be some follow-up work for @kyouko-taiga to do that I can't address.  That includes:
- elimination of SourceRange.eliminateFIXME
- serializing actual source file contents rather than reading them off disk.

2023-01-20 08:51 UTC, kyouko-taiga commented on Sources/CLI/main.swift
>      // Log the location, if available.
```suggestion
    // Log the location.
```

2023-01-20 08:55 UTC, kyouko-taiga commented on Sources/Core/AST/Decl/AssociatedTypeDecl.swift
>    /// The source range of the declaration's introducer, if any.
```suggestion
  /// The source range of the declaration's introducer.
```

There's probably a lot of "...., if any" comments in the docs of all nodes.

2023-01-20 09:05 UTC, kyouko-taiga commented on Sources/Core/AST/Expr/ParameterTypeExpr.swift
> -  public var isConventionSynthesized: Bool { convention.origin == nil }
I think there was something elegant about this property that makes me believe perhaps the fact that something has been synthesized should be encoded in the origin. That might be how to replace your `eliminateFIXME`.

2023-01-20 09:14 UTC, kyouko-taiga commented on Sources/FrontEnd/Parse/Parser.swift
> +    origin = state.range(from: startIndex)
It's wrong because introducer.origin might be `eliminateFIXME`(formerly `nil`) if `buildSubscriptImplDecl` was called to parse a subscript implementation without an introducer. For example:

```
property foo: Int { 0 } // let introducer is synthetic
```

In that case, we need to get the first position of the contents of the body.

2023-01-20 09:16 UTC, kyouko-taiga commented on Sources/FrontEnd/Parse/Parser.swift
> +            synthesized: tree.0 == nil  // FIXME: @kyouku-taiga should check this for correctness.
That's correct.

2023-01-20 09:18 UTC, kyouko-taiga requested changes
There's an invalid change in the parser. I left an inline comment. Let me know if you need my help to fix.

2023-01-20 15:21 UTC, dabrahams commented on Sources/Core/AST/Expr/ParameterTypeExpr.swift
> -  public var isConventionSynthesized: Bool { convention.origin == nil }
I disagree.  Whether to add a feature (a.k.a. complexity) should be based on whether the problem demands it, not on whether we think there's something elegant about it.  BUT: if you really want to know if something is synthesized, you only need to check if its sourceRange start == end.  These synthesized bits should all (or nearly all) have locations in real source.

2023-01-20 20:35 UTC, dabrahams commented on Sources/FrontEnd/Parse/Parser.swift
> +    origin = state.range(from: startIndex)
Fixed?

2023-01-20 20:36 UTC, dabrahams commented on Sources/FrontEnd/Parse/Parser.swift
> +            synthesized: tree.0 == nil  // FIXME: @kyouku-taiga should check this for correctness.
```suggestion
            synthesized: tree.0 == nil
```

2023-01-23 19:03 UTC, kyouko-taiga approved these changes
LGTM

2023-01-23 19:04 UTC, kyouko-taiga commented on Sources/FrontEnd/Parse/Parser.swift
> +    origin = state.range(from: startIndex)
Yep, good job.

2023-01-23 19:05 UTC, merged

2023-01-23 19:12 UTC, dabrahams commented on Sources/Core/AST/Expr/ParameterTypeExpr.swift
> -  public var isConventionSynthesized: Bool { convention.origin == nil }
Oops; I meant to remove it entirely!  It isn't used anywhere.  That was my point about whether the problem demands it

2023-01-23 19:14 UTC, kyouko-taiga commented on Sources/Core/AST/Expr/ParameterTypeExpr.swift
> -  public var isConventionSynthesized: Bool { convention.origin == nil }
Ah, "au temps pour moi"!

I operated under the assumption it was used in the type checker.