Make sure that generated CXX code compiles
val-lang/val pull request #269
Opened 2023-01-25 18:05 UTC by lucteo

Currently for a basic example like Factorial, we did not generate compilable C++ code.

This PR fixes that, by doing two things:
* ensuring the name of the module and the names of the written files match (don't include "Main.h", when we generate "main.h")
* When the program contains a `main` function, add a top-level `main` function in the generated CXX code that just calls the one from the appropriate module.

2023-01-26 01:29 UTC, kyouko-taiga commented on Examples/factorial.val
> +public fun main() -> Int {
I should add this to the specification, but that code should be illegal, I think. The problem is that `Int` represent 64-bit integers in Val (at least on 64-bit platforms), so it shouldn't be used to return exit statuses.

Eventually, the specification will say that the entry point of a Val program can be declared as either of the following options:
- `public fun main()`
- `public fun main() -> Int32`
- `public fun main(arguments: Arguments)`

For this PR, I would suggest truncating the result of `factorial` to `Int32`. There's an initializer that does that already in the standard library: https://github.com/val-lang/val/blob/ef26e55061399c0c446935e8562902be59c518f6/Library/Core/Int32.val#L9

2023-01-26 01:35 UTC, kyouko-taiga commented on Examples/factorial.val
> +  factorial(6)
In fact, I think we shouldn't return the result of `factorial(6)` as the exit status of a program. Although it's traditionally a 32-bit integer, exit statuses can only range from 0 to 255, whereas 6! = 720.

2023-01-26 01:36 UTC, kyouko-taiga requested changes
We can't use the result of `factorial(6)` as the exit status of a program for two reasons:
1. `factorial(_:)` returns a 64-bit integer and exit codes must be represented by `Int32`
2. 6! is too large if I'm not mistaken.

2023-01-26 19:04 UTC, lucteo commented on Examples/factorial.val
> +  factorial(6)
I would argue that we need to be able to return a status code from Val to the `main` function. Indeed, on most platforms this gets truncated to an 8-bit (unsigned?) integer. Also, in C++, the type of `int` can actually be 64 bits wide (although not on any major platforms it's only 32 bits).

2023-01-26 19:06 UTC, lucteo commented on Examples/factorial.val
> +public fun main() -> Int {
I can do the first 2 cases as part of this PR, but I would defer the third one to later.

2023-01-26 20:05 UTC, kyouko-taiga commented on Examples/factorial.val
> +  factorial(6)
I'm not contesting that we should be able to return a status code, only that it shouldn't be Val's `Int`.

As for the 8-bit requirement, I think we should keep in mind that we'll probably need to stick with something that works on most platforms if we want to implement tests down the line.

2023-01-26 20:07 UTC, kyouko-taiga commented on Examples/factorial.val
> +public fun main() -> Int {
That's completely fine. I'll define in the specification that `main() -> X` is ill-formed unless `X` is `Int32` anyway.

As for the third case, we'll have to decide what `Arguments` is exactly before we can do anything. So yes, let's skip it for now.

2023-01-28 11:45 UTC, lucteo commented
Looking at this PR, with the current translation of types, the only thing that I would change (more or less) is the example.
To properly fix the example, we need to change how we generate code for basic types. We agreed that this will be done soon after.

2023-01-28 22:17 UTC, dabrahams commented
Err, <img width="702" alt="image" src="https://user-images.githubusercontent.com/44065/215293584-1d2f85c2-4e09-4edd-9649-e101e5eaf7fa.png">

2023-01-31 13:19 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXCodeWriter.swift
> +    // If we need to generate the CXX entry point for the mdule, write the `main` function here with the proper body.
```suggestion
    // Write a CXX `main` function if the module has an entry point.
```

2023-01-31 13:28 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXCodeWriter.swift
> +      target.write("int main()")
Also, shall we consider using clang-format (see #295)?

2023-01-31 13:29 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXModule.swift
> +  /// If the module contains a `main` function, this will be set to call that function in what will be the CXX program entry point.
```suggestion
  /// Indicates whether this module contains an entry point (i.e., a `main` function).
```

2023-01-31 13:33 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +    // If this is the `main` function of the program, generate the body that needs to be the CXX entry point.
```suggestion
    // If this is the Val's entry point, generate a CXX entry point body that calls it.
```

2023-01-31 13:35 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +  /// Translate the body of the entry-point for the CXX program.
```suggestion
  /// Writes the body of a CXX entry point calling `decl` to `cxxEntryPointBody`, knowing it output type is
  /// expressed by `output` and writing CXX nodes to `module`.
```

2023-01-31 13:41 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +  /// Translate the body of the entry-point for the CXX program.
Why not returning the `CXXStmt` computed by the function rather than mutating `self`? If it was written that way, would the function still have to be mutable?

Also, why do you need to take `output` as parameter? Can't it be derived from `decl`? If the problem is that you don't want to repeat L49-57, a probably better solution would be to factor out this code in a function `(FunctionDecl.Typed) -> AnyType` so that you can write:
```swift
let output = CXXTypeExpr(outputType(decl), ast: program.ast, asReturnType: true)!
```

2023-01-31 13:43 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +    let orig = AnyNodeID.TypedNode(decl)
```suggestion
    let valNode = AnyNodeID.TypedNode(decl)
```

2023-01-31 13:44 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +    let callMainExpr = CXXFunctionCallExpr(
```suggestion
    let callToMain = CXXFunctionCallExpr(
```

2023-01-31 13:45 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +      stmts.append(
Very minor: if I'm not mistaken, the standard says `main` doesn't have to return anything. You could potentially save this line for conciseness.

2023-01-31 13:46 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +    module.cxxEntryPointBody = CXXScopedBlock(stmts: stmts, original: orig)
We should favor returning values over adding side effects in general.

2023-01-31 13:49 UTC, kyouko-taiga requested changes
Great work!

I'm think the API of `emit(programEntryPointFor:withOutputType:into:)` could be reworked a little. I left inline comments. Other suggestions are minor.

2023-01-31 21:33 UTC, lucteo commented on Sources/CodeGen/CXX/CXXCodeWriter.swift
> +      target.write("int main()")
That would break the indentation of `int main()`.
I could technically look for '\n' in the given string and break the string at those points, but that feels hackish.

2023-01-31 21:33 UTC, lucteo commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +  /// Translate the body of the entry-point for the CXX program.
I need to revisit this after #285 gets merged.

One possible problem I see is that we might have multiple `main` functions in the same module/program.

2023-01-31 21:33 UTC, lucteo commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +    let orig = AnyNodeID.TypedNode(decl)
will be deleted after #285

2023-01-31 21:33 UTC, lucteo commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +      stmts.append(
I did not know that. Thank you! Will change.

2023-01-31 21:33 UTC, lucteo commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +    module.cxxEntryPointBody = CXXScopedBlock(stmts: stmts, original: orig)
Agree.
In this case I did not see a simple and good solution, without inventing a monadic behaviour. We need to parse multiple entities, and one of them might result in something that needs to be stored in the top-level module (which can be several levels up in the call hierarchy)

Do you see a simple/good solution?

2023-01-31 21:35 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXCodeWriter.swift
> +      target.write("int main()")
I retract my comment but I really think this formatting stuff should be offloaded to `clang-format`. That's out of scope for this PR though.

2023-01-31 21:36 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +  /// Translate the body of the entry-point for the CXX program.
Multiple `main` functions in C++? I'll make sure it's not possible to have multiple main functions in Val (i.e., specify that a program with more than one `main` function is ill-formed).

2023-01-31 21:43 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +    module.cxxEntryPointBody = CXXScopedBlock(stmts: stmts, original: orig)
I'm not sure to follow. `emit(programEntryPointFor:withOutputType:into)` is called specifically to produce the `CXXStmt` that is assigned to `cxxEntryPointBody ` unconditionally. Why can't we have the caller(s) make this assignment?

Specifically, rather than doing:
```swift
if identifier.description == "main" {
  emit(programEntryPointFor: decl, withOutputType: output, into: &module)
}
```
we'd have:
```swift
if identifier.description == "main" {
  module.cxxEntryPointBody = emit(programEntryPointFor: decl, withOutputType: output, into: &module)
}
```

2023-02-03 21:12 UTC, lucteo commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +  /// Translate the body of the entry-point for the CXX program.
in my new PR, took advantage of this, and the fact that the `main` function is always at top-level. This way, I don't have to recurse down too much.

2023-02-03 21:13 UTC, lucteo commented on Sources/CodeGen/CXX/CXXTranspiler.swift
> +    module.cxxEntryPointBody = CXXScopedBlock(stmts: stmts, original: orig)
I went another way and made another traversal of the top-level decls. I took advantage of the fact that we only have `main` at top level. This way, the logic is simple and doesn't require any mutation (there are just a few levevels that I need to pass the restulting `CXXStmt` up.

2023-02-03 21:14 UTC, lucteo commented
Abandoing in the favor of #322

It was easier to start over than to do the merge, and then make the required changes

2023-02-03 21:14 UTC, closed without merging