Add tests that execute generated executable
val-lang/val pull request #361
Opened 2023-02-08 20:42 UTC by lucteo

Implements #345.

At this point, we add just one test to prove the flow: Val type checking -> C++ transpilation -> C++ compilation -> execution of the executable.

Contains refactoring to move test annotations functionality in a dedicated testing-only library.

2023-02-15 19:58 UTC, kyouko-taiga commented on Tests/TestUtils/XCTest+Shims.swift
> +  public final class XCTSourceCodeLocation: Hashable {
Initializer probably ought to be public too. Do the tests pass on non macOS platforms?

2023-02-15 19:59 UTC, kyouko-taiga commented on Tests/TestUtils/XCTest+Shims.swift
> +  public final class XCTSourceCodeLocation: Hashable {
Looks like they do.

2023-02-15 20:14 UTC, kyouko-taiga requested changes
It goes in the direction of what we discussed, but I think there's another way to organize this stuff.

I would not have `ExecutionTests` under the `ValCommand` target. These tests do not directly relate to `ValCommand`. They are testing the transpiler.

You could drive the compilation the same way `CXXTests` does and have your `run(_:withArguments:)` method be defined as a member of the `XCTestCase` subclass handling your execution tests. If you do it that way, there's no need to promote `Utils` to a target and it can stay under `ValTests`.

2023-02-17 17:03 UTC, kyouko-taiga commented
I am still not convinced that you need to use the annotation system to run your end-to-end tests. The patch is bringing _a lot_ of complexity. It's creating a new target, breaking encapsulation of several components, and defining a new test annotation. All of that to write `//! run` at the top of every test case in `EndToEndTests`.

It's far simpler to just compile a program, execute it, and look at its exit status. I bet all test cases will do just that anyway for the foreseeable future.

Once you can show me sufficiently complex test cases where we _really_ need to inspect the standard output, we can re-open this idea. Until then, I think we should just stick to a simpler approach. I can create a PR to show you what I have in mind if you want.

2023-02-17 19:01 UTC, lucteo commented
@kyouko-taiga : it is true that I don't necessarily need the annotation system for this PR. But there are two things that we should be adding to end-to-end tests in the near-medium term:
* check the output of the program (we can generate programs that write to the console with very few changes)
* ability for the generated programs to capture the command line arguments

I would hate to remove the common testing code now just to add it soon after.
Moreover, we start to have shared testing abstractions between our three testing targets.

2023-02-17 19:05 UTC, kyouko-taiga commented
> check the output of the program (we can generate programs that write to the console with very few changes)

Yes and no. We can hack a solution quickly, but implementing a proper print will take longer. Regardless, I highly doubt we absolutely need to print anything on the console for the time being. As I mentioned, we can start with e2e tests that just look at the exit status.

> ability for the generated programs to capture the command line arguments

This is definitely not a high priority for now.

> I would hate to remove the common testing code now just to add it soon after.

I'm saying that we won't know how much sharing we actually need until we'll have actual use cases for the shared features.

2023-02-19 10:05 UTC, lucteo commented
@kyouko-taiga : I really need in the near future to have tests that produce output, and also be parameterized. Otherwise, the end-to-end tests loose most of what they need to do. I wanted to put up a followup PR this weekend to show that this is relatively easily achieved, but did not get to it.

2023-02-19 11:01 UTC, kyouko-taiga commented
We need to discuss visions, because I think there's a mismatch. I'm sorry I put a roadblock on your work here, but this change doesn't go in the direction I'd like.

2023-02-19 17:55 UTC, dabrahams commented
Might need to be today if you want me involved. I’m on vacation next weekSent from my iPhoneOn Feb 19, 2023, at 3:01 AM, Dimi Racordon ***@***.***> wrote:﻿
We need to discuss visions, because I think there's a mismatch. I'm sorry I put a roadblock on your work here, but this change doesn't go in the direction I'd like.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because your review was requested.Message ID: ***@***.***>

2023-02-19 19:11 UTC, dabrahams commented
For perspective, "just look at the exit status" may sound on its face like it is too limiting, but I think it works if the test programs themselves include assertions of expected intermediate results, rather than trying to compare printed output.  Does that help, @lucteo?

2023-02-19 19:19 UTC, dabrahams requested changes
See comments

2023-02-19 19:19 UTC, dabrahams commented on Tests/TestSupport/AnnotatedValFileTest.swift
> +  /// - Parameter `testCaseDirectory`: where the test files are searched.
Does it have to be absolute?  If not, relative to what is it interpreted?

You changed the name of the parameter but didn't change the place where it appears in the summary fragment.  You removed important information about how to understand it, in favor of redundantly repeating its high-level meaning.

2023-02-19 19:19 UTC, dabrahams commented on Tests/TestSupport/AnnotatedValFileTest.swift
> +  ///   - `testCaseDirectory`: where the test files are searched.
Replaced important information with redundant info.

2023-02-19 19:19 UTC, dabrahams commented on Tests/ValTests/CXXTests.swift
> +      in: Bundle.module.url(forResource: "TestCases/CXX", withExtension: nil)!,
It is inot an improvement that now I need to read this mysterious `Bundle` incantation every time `checkAnnotatedValFiles` is called.

2023-03-11 09:59 UTC, lucteo commented
Fixed with #496

2023-03-11 09:59 UTC, closed without merging