Add possibility to format generated C++ code with clang-format.
val-lang/val pull request #388
Opened 2023-02-13 19:43 UTC by lucteo

If `clang-format` is found in the path, allow the CXXCodeWriter to use it to format the output C++ code.

2023-02-15 22:17 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CodeTransform.swift
> +public func identity() -> CodeTransform {
I'm a bit uncomfortable having `identity` be introduced in the global namespace, as a public symbol. I think there's a better way to initialize the code writer (see other comment).

2023-02-15 22:19 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXCodeWriter.swift
> +  public init(formatter: @escaping CodeTransform = identity()) {
```suggestion
  public init(formatter: CodeTransform? = nil) {
```

IIUC, that's what your `identity` function is representing: the absence of any transformation.

2023-02-15 22:20 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CodeTransform.swift
> +public typealias CodeTransform = (String) -> String
This should be in the namespace of `CXXCodeWriter`

2023-02-15 22:21 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXCodeWriter.swift
> +    return formatter(target.code)
```suggestion
    return formatter?(target.code)
```

2023-02-15 22:22 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXCodeWriter.swift
> +    return formatter(target.code)
```suggestion
    return formatter?(target.code)
```

2023-02-15 22:22 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/CXXCodeWriter.swift
> +  private let formatter: CodeTransform
```suggestion
  private let formatter: CodeTransform?
```

2023-02-15 22:23 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/ClangFormatTransformation.swift
> +public func clangFormatTransformation(_ executable: URL, style: String = "llvm") -> (
```suggestion
public func makeClangFormatter(_ executable: URL, style: String = "llvm") -> (
```

2023-02-15 22:26 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +
```suggestion
    let codeFormatter: CodeTransform? = (try? find("clang-format")).map({ clangFormatTransformation(URL(fileURLWithPath: $0!)) })
```

Can be improved if `clangFormatTransformation` does the URL construction from a path.

2023-02-15 22:28 UTC, kyouko-taiga requested changes
Great work. I'm very excited about this change!

I think there's a way to avoid introducing an `identity` function in the global namespace. See my inline comments.

2023-02-22 19:20 UTC, lucteo commented on Sources/CodeGen/CXX/CodeTransform.swift
> +public typealias CodeTransform = (String) -> String
@kyouko-taiga : If `CXXCodeWriter` disappears in the near future, where do you think it's better to put `CodeTransform`?

For me, keeping it here doesn't seem that bad (after removing `identity()` function)

2023-03-06 20:35 UTC, kyouko-taiga commented on Sources/CodeGen/CXX/ClangFormatter.swift
> +  return { code in
```suggestion
  { (code) in
```

2023-03-06 20:36 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +    // >>>>>>> upstream/main
What's this?

2023-03-06 20:37 UTC, kyouko-taiga reviewed
There seems to be leftover comments in the PR. Apart from that and a couple of minor suggestions, LGTM.

2023-03-07 18:06 UTC, lucteo commented on Sources/ValCommand/ValCommand.swift
> +    // >>>>>>> upstream/main
:( apparently I didn't properly save the file.

2023-03-07 20:11 UTC, merged