Fixed binary file generation problem in windows
val-lang/val pull request #414
Opened 2023-02-17 15:19 UTC by C-BJ

2023-02-17 15:29 UTC, C-BJ commented
I don't know what's wrong with CI

2023-02-17 15:42 UTC, kyouko-taiga commented
`main` is failing; working on it.
I'll re-run your PR once it's fixed.

2023-02-18 07:01 UTC, C-BJ commented
I have cleaned all the commit

2023-02-18 07:06 UTC, C-BJ commented
I have nothing to do with this CI failure(The CI failure I caused earlier has been resolved)

2023-02-18 12:32 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +
This change would deserve to be factored out in a function so we can document the intent.

2023-02-18 12:34 UTC, C-BJ commented on Sources/ValCommand/ValCommand.swift
> +
Create a separate function?

2023-02-18 12:34 UTC, kyouko-taiga commented on .gitignore
> +**.exe
```suggestion
# Windows
**.exe
```

2023-02-18 12:35 UTC, kyouko-taiga commented on .gitignore
> +**.exe
This section should come next to `macOS`, for consistency.

2023-02-18 12:36 UTC, kyouko-taiga requested changes
See inline comments.

2023-02-18 12:38 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +
Yes, exactly. Maybe:

```swift
/// Returns the path for an executable `name` at given `prefix`.
private func executablePath(_ prefix: URL, _ name: String) -> String {
  ...
}
```

2023-02-18 13:19 UTC, C-BJ commented
Sorry, I did something wrong.

2023-02-18 15:58 UTC, kyouko-taiga approved these changes
Looks good, thanks.

2023-02-18 15:59 UTC, merged