Support the MSVC and GCC
val-lang/val pull request #450
Opened 2023-02-23 14:05 UTC by C-BJ

Closes: #431

2023-02-23 16:33 UTC, kyouko-taiga commented on .github/workflows/build-and-test.yml
> +name: CI
Why is the length of this name an issue?

"CI" is less descriptive than "Build and test". We might want to add other workflows to CI in the future.

2023-02-23 16:36 UTC, kyouko-taiga commented on README.md
> +- `--emit binary` (default): Produce an executable (Clang / MSVC / GCC is required for now).
I'd rather have the command line accept an explicit parameter to select the C++ compiler to use and default to clang if the flag isn't set. Val will only grow closer to clang as time goes, so it makes sense to be opinionated here.

2023-02-23 16:36 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +    let whichCompiler = ProcessInfo.processInfo.environment["ValCXXCompiler"] ?? ""
This value should be read from a command line argument.

2023-02-23 16:39 UTC, kyouko-taiga requested changes
Thanks a lot for this work!

I'd like to keep MVSC and GCC as nice-to-have features rather than committing to support those compilers. One way to alleviate our commitment is to have our compiler allow the user to select the compiler they want to use as a command line argument. Then anyone will be free to opt-out clang to use MVSC, GCC, or anything else.

That also means we don't need to hardcode an arbitrary order in our compiler.

2023-02-24 12:06 UTC, C-BJ commented
I finished this PR, btw
![image](https://user-images.githubusercontent.com/62678643/221174768-2507509a-ec95-41c8-a24b-e6ae39dfc11d.png)
Does the description of the repository need to be changed
And why aren't Github discussions in the main repository?

2023-02-24 14:49 UTC, kyouko-taiga commented
> I finished this PR, btw

Thanks, I'll look at the changes later today.

> Does the description of the repository need to be changed

Why would the description have to change?

> why aren't Github discussions in the main repository? Wouldn't that make easier to access(jump)?

We thought it would be best to keep all discussions not related to the compiler implementation in a separate repository. You can easily access them by hoping through the organization's page.

2023-02-24 14:59 UTC, C-BJ commented
I simply thought we would have the Library in this repository, so I just mention it

2023-02-25 13:22 UTC, kyouko-taiga commented on .github/workflows/build-and-test.yml
> +    name: Swift 5 on ${{ matrix.host.os }} with Clang backend
This change is unnecessary. We'll always go for the clang backend, at least for the foreseeable future.

2023-02-25 13:24 UTC, kyouko-taiga commented on README.md
> +  - `Clang` / `MSVC` / `GCC` is required for now. But only `Clang` has received the formal support.
After discussing with other contributors, we've decided that it's better to not even mention support for other compilers. We'll target clang and the ability to use another compiler if you want, without any guarantee.
```suggestion
```

2023-02-25 13:27 UTC, kyouko-taiga commented on README.md
> +  - If you want to use MSVC, be sure to use Visual Studio Developer Command Prompt or Visual Studio Developer PowerShell
```suggestion
  - Note: by default, C++ files will be compiled with clang. Use `--cc /some/c++/compiler` to use another compiler.
  - Note to MSVC users: be sure to use Visual Studio Developer Command Prompt or Visual Studio Developer PowerShell.
```

2023-02-25 13:36 UTC, kyouko-taiga requested changes
After discussing with other contributors, we've decided that we should focus on one C++ compiler rather than hinting about more support.

The current position is that supporting three major C++ compilers is too much work at this stage of the project. Even if support is not "formal", users will rightfully expect most features to just work if there's a gcc or mvsc option built-in the command line.

Our priority is to get a working version of Val and use transpilation to explain the language's semantics in terms of C++. It is possible that we'll work toward supporting the three major C++ compilers in the future, once we shift our focus on interoperability.

In the context of the current PR, I suggest you modify the Val compiler command line so that it can accept the path/name of a custom C++ compiler along with another option to forward flags to that C++ compiler. The idea is to be able to execute:
```bash
valc --cc gcc --cc-flags -O3 factorial.val
```

2023-02-25 13:52 UTC, C-BJ commented
After we got the LLVM back end, wasn't it difficult to support interoperability support for multiple versions of CXXCompiler?
As far as I know, Carbon only plans to interoperate with Cpp when using the Clang compiler
Or maybe you're not talking about the LLVM back end?
@kyouko-taiga

2023-02-25 14:00 UTC, kyouko-taiga commented
> After we got the LLVM back end, wasn't it difficult to support interoperability support for multiple versions of CXXCompiler?

Yes and no.

Currently, the transpilation story is completely orthogonal to LLVM. That's because the transpiler just walks Val ASTs and generate C++ text. We can continue to operate that way as long as we can afford a second-class interoperability from C++ to Val, i.e., use a C++ API inside a Val program.

In that picture, LLVM is just another backend and generating LLVM IR is no different than generating Javascript sources.

Once we want C++ to Val interoperability, however, we'll need a way to read C++ sources to generate the corresponding Val APIs and necessary glue code. I plan on using clang to do that, meaning there's a connection to LLVM at this point. I have almost no idea how we'll deal with ABI, but I suspect that's the point where we'll diverge more and more from other compilers.

2023-02-26 00:19 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +  private var ccFlags: [String] = ["Empty"]
Why the need for a particular value and not simple:
```suggestion
  private var ccFlags: [String] = []
```

2023-02-26 00:21 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +  private var customizeCXXCompiler: CXXCompiler = .clang
```suggestion
  private var cxxCompiler: CXXCompiler = .clang
```
It's not necessarily custom; we'll always use this value IIUC.

2023-02-26 00:22 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +        if ccFlags != ["Empty"] {
```suggestion
        if !ccFlags.isEmpty {
```
Assuming we can declare `ccFlags: [String] = []` as I suggested.

2023-02-26 00:24 UTC, kyouko-taiga reviewed
Starting to look very good. I left a few inline comments.

2023-02-26 00:24 UTC, C-BJ commented on Sources/ValCommand/ValCommand.swift
> +  private var ccFlags: [String] = ["Empty"]
Sorry, my fault

2023-02-26 13:43 UTC, C-BJ commented
@kyouko-taiga

2023-02-26 13:48 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +        }
```suggestion
        var arguments = ccFlags.map({ "/\($0)" })
        
        for i in (0 ..< ccFlags.count) {
          arguments.append("/" +  ccFlags[i])
        } 
```

2023-02-26 13:49 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +    }
```suggestion
    arguments += ccFlags.map({ "-\($0)" })
```

2023-02-26 13:50 UTC, kyouko-taiga commented on README.md
> +  - Note: You can specify parameters for the CXX compiler to use. like `--cc-flags O3`.
```suggestion
  - Note: You can specify parameters for the CXX compiler to use (e.g., `--cc-flags O3`).
```

2023-02-26 13:54 UTC, kyouko-taiga commented on README.md
> +    - You can also add more than one such parameter.
```suggestion
    - You can also add more than one parameter (e.g., `--cc-flags O1 g`)
```
Or maybe I misunderstood your point here.

Another question I have, what happens if we want to pass a flag with an argument?
That can be addressed in a separate PR if this one doesn't support it.

2023-02-26 14:16 UTC, C-BJ commented on README.md
> +    - You can also add more than one such parameter.
> Another question I have, what happens if we want to pass a flag with an argument?

Let's do that later in another PR

2023-02-26 14:17 UTC, C-BJ commented on README.md
> +    - You can also add more than one such parameter.
Actually we need `--cc-flags O1 --cc-flags g` instead `--cc-flags O1 g` I'm going to make this clear

2023-02-26 14:18 UTC, kyouko-taiga approved these changes
Really nice!

Thanks for the hard work.

2023-02-26 14:24 UTC, C-BJ commented
I think this PR can be merge @kyouko-taiga

2023-02-26 14:41 UTC, C-BJ commented
I think that's all done @kyouko-taiga

2023-02-26 15:11 UTC, merged