Enable Windows CI
val-lang/val pull request #521
Opened 2023-03-15 12:10 UTC by C-BJ

Fixes: #252
This PR uses the code in #520
https://github.com/C-BJ/val/actions/runs/4425956093/jobs/7761649842

This is a solution for once and for all. Since I've come to realize that the CI flake issue is not something we can easily fix (many project, regardless of programming language, have similar problems), I've tried to find a new approach. In this PR, we only let Windows build and debug in Release mode, reducing the probability of CI flake and saving time. When the build or test fails, the CI will try again, and if it fails again, the entire CI will fail, otherwise the CI will be marked as a success.

I think the Github Action link above explains the whole thing pretty clearly

2023-03-15 12:20 UTC, C-BJ commented
But, I am not sure whether the build or test's retry steps will work properly (because I cannot test). If there is any problem, please feel free to tell me later.

2023-03-17 12:33 UTC, C-BJ commented
> > many project, regardless of programming language, have similar problems
> 
> That would seem to imply that Microsoft, who owns both GitHub and Windows, can't make them work together reliably. Am I reading that right, or is there something more that all these projects have in common?

I think CI flake in Windows has nothing to do with Github Action and everything to do with Windows itself.

2023-04-17 13:32 UTC, C-BJ commented
CI errors are expected because https://github.com/val-lang/Swifty-LLVM/pull/9 need to be merged first. @kyouko-taiga

2023-04-17 15:30 UTC, kyouko-taiga commented
Before we consider moving forward with the retry trick to handle Windows CI failures, have you looked into this answer @C-BJ https://github.com/orgs/community/discussions/26933 ? Could it be related to our problems?

2023-04-22 06:22 UTC, C-BJ commented
https://forums.swift.org/t/stability-of-swift-on-windows/63610/30

2023-04-22 11:33 UTC, kyouko-taiga commented
I see. Well then let's go ahead with your approach. I'll merge your PR on Swifty-LLVM and this one asap.

I made some changes on `main` that have surely introduced some issues on Windows. Now `valc` requires access to a support library that is compiled separately. On Unix, it gets installed at `/use/local/lib` be default but I don't know what should be done for Windows.

Here's an overview of how things work on Unix:
- The target `Support` (in `Sources/`) contains C/C++ files that implement runtime and support functions.
- We use SPM to compile this target, resulting in object files in `.build/release/Support.build/src`
- We gather all of these files in a library named `liberal_support.a; that's the support library
- We create a SDK which is just a directory with a `lib/` sub-directory containing that library
- We install that SDK at `/usr/local/lib/val`

You can see all steps in `Tools/install.sh`. I guess we should create a similar script for Windows.

This approach is probably not a long-term solution. But I am really not an expert with C/C++ build tools so I just hacked something that works locally and with CI. If you know a better, more portable way to move forward, I'm all ears!

2023-04-22 13:29 UTC, C-BJ commented
I'll look into it as soon as I can, but I've been a little busy

2023-04-22 13:29 UTC, kyouko-taiga commented
No worries. Let me know if you need any help.

2023-04-22 13:33 UTC, C-BJ commented
There is another problem, I now use the Windows LLVM version in https://github.com/c3lang/win-llvm. Do you think we need to separate maintain a repository? Compile LLVM ourself?

2023-04-22 13:36 UTC, kyouko-taiga commented
I don't think so. Why not simply use this repository to get LLVM for the Windows CI integration and continue to rely on the approaches currently in place for macOS and Linux?

2023-04-22 13:37 UTC, C-BJ commented
sorry wdym?

2023-04-22 13:41 UTC, C-BJ commented
I know it doesn't make any difference, it's just a lot of languages do it, I'm just asking

2023-04-22 13:43 UTC, kyouko-taiga commented
CI is configured differently for macOS and linux. On macOS, we download and install LLVM using a GitHub action ([install-llvm-action](https://github.com/KyleMayes/install-llvm-action)). On Linux, we use `apt` (see the Dockerfile in `.devcontainer/`).

I guess that on Windows we can refer to this other version that you're using. If I understand correctly, that's what you've done on Swifty-LLVM.

2023-04-22 13:44 UTC, kyouko-taiga commented
> I know it doesn't make any difference, it's just a lot of languages do it, I'm just asking

Ah, I see. Perhaps we should continue with the current setup for the time being. There's a value having the CI confirm that everything works as expected if you're downloading and installing LLVM from sources, as it is likely what most user would do locally on their machine.

2023-04-22 13:51 UTC, C-BJ commented
Actually what I'm saying is, should we build LLVM ourselves instead of using something that someone else has already built, actually we don't have any problem using someone else's build, so I think we should do that later only when we have additional needs for LLVM builds

2023-04-22 13:56 UTC, kyouko-taiga commented
I have to admit that I don't have a strong opinion on the subject. If you think it's better to use someone else's build (like as you said many languages do), then I'm fine with that.

2023-04-22 13:58 UTC, C-BJ commented
sorry, I mean other languages mostly build their own. 
also it's a small thing, when we need it, we build it ourselves

2023-04-23 14:54 UTC, C-BJ commented
> I see. Well then let's go ahead with your approach. Thanks a lot for investigating! I'll merge your PR on Swifty-LLVM and this one asap.
> 
> I made some changes on `main` that have surely introduced some issues on Windows. Now `valc` requires access to a support library that is compiled separately. On Unix, it gets installed at `/use/local/lib` be default but I don't know what should be done for Windows.
> 
> Here's an overview of how things work on Unix:
> 
> * The target `Support` (in `Sources/`) contains C/C++ files that implement runtime and support functions.
> * We use SPM to compile this target, resulting in object files in `.build/release/Support.build/src`
> * We gather all of these files in a library named `liberal_support.a; that's the support library
> * We create a SDK which is just a directory with a `lib/` sub-directory containing that library
> * We install that SDK at `/usr/local/lib/val`
> 
> You can see all steps in `Tools/install.sh`. I guess we should create a similar script for Windows.
> 
> This approach is probably not a long-term solution. But I am really not an expert with C/C++ build tools so I just hacked something that works locally and with CI. If you know a better, more portable way to move forward, I'm all ears!

I'm pretty much done. I'll finish it then commit it tomorrow or the day after tomorrow. @kyouko-taiga

2023-04-24 14:25 UTC, kyouko-taiga commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Factorial.val")
I remember we had a discussion about this but I don't remember the conclusion. Why can't we use `Bundle.module.url(forResource: "TestCases", withExtension: nil)!` on Windows?

The problem with your approach is that we'll have to edit this file every time we add a new test will a long list of hard-coded filenames, the number of end-to-end tests is expected to grow significantly.

We're using `Bundle.module.url` in several places. That's how collect the test cases of the parser, the type checker, and the IR emitter. Are these tests broken on Windows too?

2023-04-24 14:26 UTC, kyouko-taiga commented
Great job @C-BJ, thanks a lot!

I just have one question I asked inline.

2023-04-24 14:28 UTC, C-BJ commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Factorial.val")
I think I can look into it a little more

2023-04-24 14:29 UTC, kyouko-taiga commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Factorial.val")
Got it.

2023-04-24 14:39 UTC, C-BJ commented
I don't know why, but there seems to be a test on Windows that goes into an infinite loop. @kyouko-taiga

2023-04-24 14:40 UTC, C-BJ commented
maybe testWhileStmtWithMultipleConditions

2023-04-24 14:42 UTC, kyouko-taiga commented
> maybe testWhileStmtWithMultipleConditions

That'd be surprising. This test is just running the parser, not running any loop. In fact, there are no execution tests that are running loops AFAIK.

2023-04-24 14:45 UTC, C-BJ commented
The local test was successful, so I don't know what the problem is

2023-04-24 14:45 UTC, C-BJ commented
https://github.com/val-lang/val/actions/runs/4787251828/jobs/8512255958
https://github.com/val-lang/val/actions/runs/4787300582/jobs/8512371120

2023-04-24 14:49 UTC, C-BJ commented
I'd like to ask you to stop these three CI
https://github.com/val-lang/val/actions/runs/4787251828/jobs/8512255958
https://github.com/val-lang/val/actions/runs/4787300582/jobs/8512371120
https://github.com/val-lang/val/actions/runs/4787431398/jobs/8512658800

2023-04-24 14:53 UTC, C-BJ commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Factorial.val")
![image](https://user-images.githubusercontent.com/62678643/234033861-da9d870e-15e5-422e-a4d3-3b520c6cd972.png)
This error appears to be due to a path slash error.
Is this a Swift error?
@kyouko-taiga

2023-04-24 15:04 UTC, kyouko-taiga commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Factorial.val")
I think so. AFAIK We're not building any path that would contain a reference to `.build/debug` so I don't think this URL has been built by us.

There's one difference between `ExecutingTests` and other Val tests. To gather test case URLs, the former always uses `Bundle.module.url` while the the latter use this method: https://github.com/val-lang/val/blob/3778b59e738aea6c7a14c24cd0ad24ad1c9ee6dd/Tests/ValTests/Utils/AnnotatedValFileTest.swift#L116-L126

I know that the condition (L120) fails on Linux and so we gather URLs `Bundle.module.url`. On macOS, however, we use the first branch (L121). If the same happens on Windows, then I guess those Val tests (parser, type checker, ...) do not use `Bundle.module.url`. That would explain why `ValTests` pass on Windows but `ExecutionTests` does not.

2023-04-24 15:09 UTC, kyouko-taiga commented
I guess everything is possible but I'd be surprised. `testCPP` only generate C++ files and then asks the OS if those files exist. If I had to guess I would expect the problem to occur with one of the tests that are running third-party tools, like `ValCommandTests.testBinary`, `ExecutionTests.testExecution`, or `ExecutionTests.testHelloWorld`. Those are calling the linker in a sub-process.

You can try to disable these tests by renaming those methods so that they have any other prefix (i.e., not start with `test`).

2023-04-24 15:09 UTC, C-BJ commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Factorial.val")
I haven't used Swift before contributing to Val, so do you have any solutions?

2023-04-24 15:23 UTC, kyouko-taiga commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Factorial.val")
I suspect the problem is caused by a bug in `Foundation` which we probably can't address directly. So my suggestion would be to use something like the `testSuite` method above to collect test URLs on Windows.

Here's a sketch of the solution:

```swift
final class ExecutionTests: XCTestCase {

  /// The URL of the `EndToEndTests/` directory of this project.
  private static let root = URL(fileURLWithPath: String(#filePath))
    .deletingLastPathComponent()

  /// Returns the Val test cases in the suite at `path` relative to root of the test target
  /// containing this file.
  ///
  /// The suite is sought at `path` relative to `EndToEndTests/`. If no such directory exists, the
  /// suite is sought at `path` relative to the root of the resource bundle associated with the
  /// current Swift module.
  private func testSuite(at path: String) throws -> [SourceFile] { 
     let p = URL(fileURLWithPath: path, relativeTo: ExecutionTests.root) 
     if p.hasDirectoryPath { 
       return try sourceFiles(in: [p]) 
     } else { 
       let s = Bundle.module.url(forResource: path, withExtension: nil)! 
       return try sourceFiles(in: [s]) 
     } 
   } 

  /// Compiles and executes all tests in `TestCases` directory, and ensures they return success.
  func testExecution() throws {
    let testCases = try testSuite(at: "TestCases")
    for testFile in testCases {
      let output = try compile(testFile.url, with: ["--emit", "binary"])
      ...
    }
  }

}
```

If my suspicion is correct, code should go through the first branch of the condition in `testSuite(at:)` on Windows. You can make sure of that with an assertion:
```
#if os(Windows)
assertionFailure()
#endif
```
If I am correct, then Windows would no longer use `Bundle.module.url` to gather URLs.

2023-04-24 17:09 UTC, kyouko-taiga commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Factorial.val")
I can implement that idea if you want but I don't have the means to run Windows myself so you'd have to do the actual testing on your end.

2023-04-24 22:47 UTC, C-BJ commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Factorial.val")
ok

2023-04-25 13:32 UTC, C-BJ commented
![image](https://user-imag.githubusercontent.com/62678643/234293150-0115dfb7-aa83-43c8-88ba-6be9db1c557e.png)
@k
@kyouko-taiga

2023-04-25 13:34 UTC, kyouko-taiga commented
Maybe `\n` isn't interpreted the same way on Windows?

2023-04-28 12:16 UTC, C-BJ commented
```Test Case 'ParserTests.testParse' started at 2023-04-28 12:04:15.741
Swift/ContiguousArrayBuffer.swift:600: Fatal error: Index out of range
Current stack trace:
0    (null)                             0x00007ffcad84e200 swift_stdlib_reportFatalErrorInFile + 134```
This error seems to occur only locally, not in CI

2023-04-28 12:20 UTC, C-BJ commented
```
> Test run started at 2023/4/28 20:19:42 <

Test Suite 'Selected tests' started at 2023-04-28 12:19:42.838
Test Suite 'EmitterTests' started at 2023-04-28 12:19:42.846
Test Case 'EmitterTests.testEmitter' started at 2023-04-28 12:19:42.846
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Unused.val:7: error: EmitterTests.testEmitter : missing expected diagnostic: 'binding 'x' was never used'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Unused.val:11: error: EmitterTests.testEmitter : missing expected diagnostic: 'binding 'z0' was never used'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Unused.val:19: error: EmitterTests.testEmitter : missing expected diagnostic: 'binding 'x10' was never used'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Unused.val:19: error: EmitterTests.testEmitter : missing expected diagnostic: 'binding 'x11' was never used'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Unused.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'binding 'x10' was never used'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Unused.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'binding 'x' was never used'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Unused.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'binding 'x11' was never used'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Unused.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'binding 'z0' was never used'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Ownership.val:76: error: EmitterTests.testEmitter : missing expected diagnostic: 'illegal mutable access'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Ownership.val:89: error: EmitterTests.testEmitter : missing expected diagnostic: 'illegal immutable access'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Ownership.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'illegal mutable access'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Ownership.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'illegal immutable access'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/NumericLiteral.val:13: error: EmitterTests.testEmitter : missing expected diagnostic: 'integer literal '128' overflows when stored into 'Int8''
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/NumericLiteral.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'integer literal '128' overflows when stored into 'Int8''
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/LocalBindings.val:7: error: EmitterTests.testEmitter : missing expected diagnostic: 'initialization of inout binding must be marked for mutation'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/LocalBindings.val:9: error: EmitterTests.testEmitter : missing expected diagnostic: 'declaration of let binding requires an initializer'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/LocalBindings.val:10: error: EmitterTests.testEmitter : missing expected diagnostic: 'declaration of inout binding requires an initializer'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/LocalBindings.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'declaration of let binding requires an initializer'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/LocalBindings.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'initialization of inout binding must be marked for mutation'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/LocalBindings.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'declaration of inout binding requires an initializer'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/ImplicitReturn.val:10: error: EmitterTests.testEmitter : missing expected diagnostic: 'missing return in function expected to return 'Int''
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/ImplicitReturn.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'missing return in function expected to return 'Int''
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/DI.val:16: error: EmitterTests.testEmitter : missing expected diagnostic: 'use of uninitialized object'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/DI.val:18: error: EmitterTests.testEmitter : missing expected diagnostic: 'use of uninitialized object'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/DI.val:24: error: EmitterTests.testEmitter : missing expected diagnostic: 'use of consumed object'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/DI.val:25: error: EmitterTests.testEmitter : missing expected diagnostic: 'use of consumed object'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/DI.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'use of consumed object'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/DI.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'use of consumed object'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/DI.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'use of uninitialized object'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/DI.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'use of uninitialized object'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Assignment.val:6: error: EmitterTests.testEmitter : missing expected diagnostic: 'left-hand side of assignment must be marked for mutation'
C:/Users/19454/Desktop/val/Tests/ValTests/TestCases/Lowering/Assignment.val:1: error: EmitterTests.testEmitter : unexpected diagnostic: 'left-hand side of assignment must be marked for mutation'
Test Case 'EmitterTests.testEmitter' failed (5.825 seconds)
Test Suite 'EmitterTests' failed at 2023-04-28 12:19:48.671
         Executed 1 test, with 32 failures (0 unexpected) in 5.825 (5.825) seconds
Test Suite 'Selected tests' failed at 2023-04-28 12:19:48.671
         Executed 1 test, with 32 failures (0 unexpected) in 5.825 (5.825) seconds
```

2023-04-28 12:20 UTC, C-BJ commented
emit cpp will enter an infinite loop under windows. There's no output, there's no end

2023-04-28 13:22 UTC, kyouko-taiga commented
I don't know exactly what I can do. It's nearly impossible for me to debug anything on Windows, because I don't have a way to run that OS. If you're lost and don't know how to proceed, I think we should put Windows support on hold until we can energy more effort on it.

I should focus my efforts on overall compiler implementation.

2023-04-28 13:42 UTC, C-BJ commented
The clang-format code doesn't work properly on windows, so I'll leave it out of the window

2023-04-29 02:58 UTC, C-BJ commented
CI passed @kyouko-taiga

2023-04-29 08:40 UTC, C-BJ commented
I think this PR is ready for final review of the merge @kyouko-taiga

2023-04-29 10:22 UTC, kyouko-taiga commented on .github/workflows/build-and-test.yml
> +    - name: Retry again on failure
```suggestion
    - name: Retry on failure
```

2023-04-29 10:22 UTC, kyouko-taiga commented on .github/workflows/build-and-test.yml
> +    - name: Retry again on failure
```suggestion
    - name: Retry on failure
```

2023-04-29 10:22 UTC, kyouko-taiga commented on .github/workflows/build-and-test.yml
> +    - name: Retry again on failure
```suggestion
    - name: Retry on failure
```

2023-04-29 10:23 UTC, kyouko-taiga commented on README.md
> +On Wondows, it will look for the `.val` directory in the user directory.
```suggestion
On Windows, it will look for a `.val` directory in the user directory.
```

2023-04-29 10:25 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +            "D:/a/val/val/.build/x86_64-unknown-windows-msvc/release/Support.build/src/.val")
```suggestion
            "D:/a/val/val/.build/x86_64-unknown-windows-msvc/release/Support.build/src/.val")
```
There's got to be another way than hardcoding paths in the source. Why not set an environment variable when you configure the CI?

2023-04-29 10:25 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +      //Get user directory
```suggestion
```

2023-04-29 10:26 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +        let codeFormatter: CodeTransform? = nil
```suggestion
        // Note: clang-format doesn't work on Windows.
        let codeFormatter: CodeTransform? = nil
```

2023-04-29 10:28 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +  /// Make Val code executable on MacOS(C++ backend)
```suggestion
```
This comment is just repeating what's already in the name of the function.

2023-04-29 10:31 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +  /// Make Val code executable on Windows and Linux(C++ backend)
```suggestion
  /// Make Val code executable on Windows and Linux.
```
We're not using C++ here.

You should just add "Windows and Linux" at the end of the existing comment. Please don't add a new line:

```swift
/// Combines the object files located at `objects` into a Linux or Windows executable file at `binaryPath`,
/// logging diagnostics to `log`.
```

2023-04-29 10:34 UTC, kyouko-taiga commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Lambda.val")
We need a way to collect these URLs programmatically. Having to update this list manually every time we add new test cases is not tenable. Since since most other contributors don't even Windows, they are likely to forget because they won't even see whether or not something changed when they run tests locally.

2023-04-29 10:36 UTC, kyouko-taiga commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Lambda.val")
If the approach I suggested doesn't work, then I vote we simply run the "Hello, World" test on Windows and skip those ones until we can figure out a solution.

2023-04-29 10:38 UTC, kyouko-taiga requested changes
Great job. I left a few comments.

The main issue is the complexity of `ExecutionTests.testExecution()`. We should avoid having so widely different behaviors. If we can't make Windows find URLs, then let's disable this test until we can figure out a solution.

I left other inline comments.

2023-04-29 12:28 UTC, C-BJ commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Lambda.val")
Can you try the method you mentioned earlier?

2023-04-29 12:34 UTC, C-BJ commented on Sources/ValCommand/ValCommand.swift
> +            "D:/a/val/val/.build/x86_64-unknown-windows-msvc/release/Support.build/src/.val")
The reason we need to do these thing in CI is because that Github Action does not seem to allow direct access to the user's directory.

2023-04-29 12:38 UTC, C-BJ commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Lambda.val")
I thought, I'll try again

2023-04-29 13:56 UTC, C-BJ commented
@kyouko-taiga

2023-04-29 15:31 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +            "D:/a/val/val/.build/x86_64-unknown-windows-msvc/release/Support.build/src/.val")
I understand. I'm suggesting that you read an environment variable that gets set by the CI configuration script before the tests are ran. You can hardcode this path in the environment variable.

I just don't want to have hardcoded paths in the source files.

2023-04-29 16:16 UTC, kyouko-taiga commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Lambda.val")
I pushed it on the branch. Can you tell me what Windows sees?

I would try to debug the following:
- See what the URL `p` generated by `ExecutionTests.testSuite` looks like (L13). It should normally be the URL of the directory containing the test cases in the target, i.e., `Tests/EndToEndTests/TestCases` relative to the root of the repository.
- If the URL looks fine, what's the value of `p.hasDirectoryPath` (L14)
- If it's true, then what does `sourceFiles(in:)` returns (L15).
- If any of the above doesn't work, then try to understand why it seems work in `ValTests`.

If none of that work, then disable `testExecution` on Windows and add an issue to fix it when you or someone else has time.

2023-04-30 07:12 UTC, C-BJ commented on Tests/EndToEndTests/ExecutionTests.swift
> +      try testValOnWindows("./TestCases/Lambda.val")
I did it.

2023-04-30 07:55 UTC, C-BJ commented
I use a very ingenious way to avoid errors, and we are able to not change the source code when we added a new test file. @kyouko-taiga

2023-04-30 09:36 UTC, C-BJ commented
I don't know how to create environment variables in CI for Windows

2023-04-30 09:40 UTC, C-BJ commented
I don't know how to create environment variables in CI on Windows

2023-04-30 10:30 UTC, kyouko-taiga commented on Tests/EndToEndTests/ExecutionTests.swift
> +    func testExecution() throws {
I might be clever but I don't understand what it is doing and why it has to be so intricate.

Please, let's try not to write large sections of code in `#if os(Windows)`. It is hard to read and will be difficult to maintain. What's the issue on Windows? Are other tests working? If so why?

Here's how things should work:
- `Bundle.module.url(forResource:withExtension:)` gives us the URL of the directory containing the test cases
- `sourceFiles(in:)` gives us a sequence with all the `.val` files in this directory.

If any of these methods are not working as expected on Windows, they should be fixed, not worked around. I don't want to merge hacks that just "happen" to work because we got lucky. We should have one single definition of `testExecution` that is nearly identical for all OSes. Other tests seem to be doing fine, so I don't think there's any reason to overengineer conditional code here.

2023-04-30 10:31 UTC, kyouko-taiga commented on Tests/EndToEndTests/ExecutionTests.swift
> +    func testExecution() throws {
> I don't know how to create environment variables in CI on Windows

Then wait a bit, because I think I'll be able to remove the need for the Val SDK (at least for now).

2023-04-30 11:23 UTC, C-BJ commented on Tests/EndToEndTests/ExecutionTests.swift
> +    func testExecution() throws {
> I might be clever but I don't understand what it is doing and why it has to be so intricate.
> 
> Please, let's try not to write large sections of code in `#if os(Windows)`. It is hard to read and will be difficult to maintain. What's the issue on Windows? Are other tests working? If so why?
> 
> Here's how things should work:
> 
> * `Bundle.module.url(forResource:withExtension:)` gives us the URL of the directory containing the test cases
> * `sourceFiles(in:)` gives us a sequence with all the `.val` files in this directory.
> 
> If any of these methods are not working as expected on Windows, they should be fixed, not worked around. I don't want to merge hacks that just "happen" to work because we got lucky. We should have one single definition of `testExecution` that is nearly identical for all OSes. Other tests seem to be doing fine, so I don't think there's any reason to overengineer conditional code here.

You can take a look, and the URL produced seem to be fine. I don't know what the problem is

![image](https://user-images.githubusercontent.com/62678643/235350325-b482142c-9047-4cc2-9a50-2686fd4b7285.png)

2023-04-30 11:28 UTC, kyouko-taiga commented on Tests/EndToEndTests/ExecutionTests.swift
> +    func testExecution() throws {
If you can't reproduce your local behavior on CI, then I'm not sure we can realistically hope to get CI working for Windows.

I'm personally out of options here, I'm really sorry. I'll ask around to see if someone has an idea, but until we can find the cause of the issue I don't want to merge hacky solutions just to appease CI.

2023-04-30 13:22 UTC, C-BJ commented on Tests/EndToEndTests/ExecutionTests.swift
> +    func testExecution() throws {
Tests also fail locally. I just want you to see if these outputs are correct?

2023-04-30 13:25 UTC, C-BJ commented
I can now make CI work correctly in my way, and do not need to make many modifications in the future, but you seem to have some requirements that I don't really understand.

2023-04-30 13:26 UTC, C-BJ commented on Tests/EndToEndTests/ExecutionTests.swift
> +    func testExecution() throws {
The test can also run on CI now, I'm just showing you the output of the url

2023-04-30 13:33 UTC, C-BJ commented
As long as we can guarantee the accuracy of CI, it's not a big deal if there's a little bit more code for windows, or if there's a specific path in the code I think

2023-04-30 13:34 UTC, C-BJ commented
We probably won't be adding platform-specific code like this again, so I don't think it's really a problem to handle Windows CI this way until we find a better solution

2023-04-30 13:35 UTC, C-BJ commented
If you're worried, I can explain the above complex code to you and make sure it's correct

2023-04-30 13:38 UTC, C-BJ commented
If you need anything, just let me know, and I'll do my best to fix it

2023-04-30 13:39 UTC, C-BJ commented
I just think that Windows CI is really more important than these little code issues

2023-04-30 13:42 UTC, C-BJ commented
@kyouko-taiga

2023-04-30 13:44 UTC, C-BJ commented
I'm sorry if these message makes you feel uncomfortable

2023-04-30 13:51 UTC, C-BJ commented on Tests/EndToEndTests/ExecutionTests.swift
> +    func testExecution() throws {
Can you run the same code in the screenshot on your system and let me take a look at the output

2023-04-30 13:53 UTC, C-BJ commented
I'm now trying to see if I can do better

2023-04-30 14:30 UTC, C-BJ commented
I found the normal solution

2023-05-01 03:54 UTC, C-BJ commented
I think I've done the rest of your request for this PR @kyouko-taiga

2023-05-04 13:41 UTC, kyouko-taiga commented on Tests/EndToEndTests/ExecutionTests.swift
> +          URL(fileURLWithPath: testFile.url.path),
This was the fix? Building a fresh URL from the existing path?

That's fine with me, but if that's the case we should add a comment to explain the workaround. As it stands, I would be tempted to refactor this code and get back to the original version.

2023-05-04 13:43 UTC, kyouko-taiga requested changes
Good job!

Conflicts are caused by the removal of the support library and C++ transpilation (we decided to put development of the latter on hold).

There's also a change in Swifty-LLVM that's likely to cause your branch to fail now. See https://github.com/val-lang/Swifty-LLVM/issues/15

2023-05-07 06:41 UTC, C-BJ commented
removal of the support library and C++ transpilation?
Why?

2023-05-07 11:27 UTC, C-BJ commented
https://github.com/val-lang/Swifty-LLVM/pull/16
@kyouko-taiga

2023-05-08 10:15 UTC, kyouko-taiga commented
> removal of the support library and C++ transpilation?
Why?

It is slowing development down. As we shifted focus on the LLVM backend to catch-up with our goal of having a 1.0 this year, keeping the C++ transpiler code around just means creating more opportunities for conflicts as we make changes to other components.

2023-05-08 13:25 UTC, C-BJ commented
> [val-lang/Swifty-LLVM#16](https://github.com/val-lang/Swifty-LLVM/pull/16) @kyouko-taiga

@kyouko-taiga

2023-05-09 15:01 UTC, C-BJ commented
There seems to be a problem with the linking process

2023-05-10 07:21 UTC, kyouko-taiga commented on README.md
> +
```suggestion
```

This is obsolete, right?

2023-05-10 07:23 UTC, kyouko-taiga commented on Tests/EndToEndTests/ExecutionTests.swift
> +      //Testing on Windows requires this not the most concise piece of assignment operation code.
```suggestion
      // Note: testing on Windows requires explicit call to `URL.init(fileURLWithPath:)`
```

2023-05-10 07:24 UTC, kyouko-taiga requested changes
Changes Look good to me. I left two small suggestions.

2023-05-10 12:17 UTC, kyouko-taiga commented
How does one link object files on windows?
On macOS we use the linker directly, not clang. Maybe you can do the same on Windows.

2023-05-10 12:22 UTC, kyouko-taiga commented
https://stackdiary.com/linux-docs/ld/

I suppose there's a utility on Windows to link object files too. Also, [LLVM has a linker](https://lld.llvm.org).

2023-05-10 12:27 UTC, C-BJ commented
```
```

2023-05-10 13:38 UTC, C-BJ commented
stdlib.h stdio.h Not supported by the Microsoft C++ standard library

2023-05-10 13:38 UTC, C-BJ commented
So I'm thinking about using other C++ standard libraries on Windows

2023-05-14 06:44 UTC, C-BJ commented
```lld-link: error: undefined symbol: aligned_alloc
>>> referenced by C:/Users/19454/AppData/Local/Temp/Val.o:(Val.77.aligned_alloc#48)

lld-link: error: undefined symbol: fdopen
>>> referenced by C:/Users/19454/AppData/Local/Temp/Val.o:(Val.77.fdopen#62)```
I can confirm that these two functions do not exist in Microsoft's C/C++ standard library
@kyouko-taiga

2023-05-14 07:11 UTC, C-BJ commented
We can use other standard libraries to solve this problem, but it's really cumbersome(I didn't try it locally) Where is the code associated with these links? Just modify it a little bit for windows

2023-05-14 07:38 UTC, C-BJ commented
My idea is to find a more generic function and than modify LibC.val to run on all three major systems

2023-05-14 07:57 UTC, C-BJ commented
I think we need Val to support conditional compilation on different systems to solve this problem

2023-05-14 08:00 UTC, C-BJ commented
I will create two `LibC.val` for Unix and Windows

2023-05-14 08:10 UTC, C-BJ commented
There is a problem with `_aligned_malloc` (alternative to `aligned_alloc` in windows) and `aligned_alloc`, the order of inputting parameters is opposite. @kyouko-taiga

2023-05-14 08:26 UTC, C-BJ commented
As you can see, now that the CI for Windows has passed, the key is to solve the problem of multi-platform conflicts. @kyouko-taiga

2023-05-14 08:43 UTC, C-BJ commented
I have found the solution

2023-05-14 09:00 UTC, C-BJ commented
I will create two `LibC.val` for Unix and Windows
But how do I modify `Library.swift` and something else?

2023-05-14 09:08 UTC, C-BJ commented
I will create two `LibC.val` for Unix and Windows
But how do I modify `Library.swift` and something else?

2023-05-14 09:11 UTC, kyouko-taiga commented
It would be nice if we can come up with a principled solution rather than hacks just to make things work.

Conditional compilation will have to be implemented in Val anyways, so that is not unreasonable to push for it. What things that worries me is that if there is a large number of functions that needs to be interfaced differently on Windows, it will be hard to create a nice system interface in Val.

I suggest you open an discussion for that [over there](https://github.com/val-lang/val-lang.github.io/discussions) so we can perhaps get some input from other members of the community.

2023-05-14 10:02 UTC, C-BJ commented
It's not a hack, it's just that Microsoft doesn't have the functions we need to use in the standard library, that's all. I'm not sure what else is possible

2023-05-14 10:03 UTC, C-BJ commented
@kyouko-taiga

2023-05-14 10:07 UTC, C-BJ commented
There isn't much that needs to be interfacing differently on Windows, just a few things that are different with the C standard library (you can imagine migrating C code from Linux to VC using only the standard library with very little modification).

2023-05-14 10:30 UTC, kyouko-taiga commented
Not saying your solution is a hack. But I'd like a unified system layer in Val that doesn't depend on the OS you're using. Providing such a layer will require us to abstract over different OSes. Since the layer must be part of Val's core library, it think it wouldn't hurt to think ahead and see how we can design a convenient way to account for these differences.

2023-05-14 10:56 UTC, C-BJ commented
It's worth mentioning that the conflict we ran into was about the C standard library, maybe we shouldn't rely on it?

2023-05-14 10:57 UTC, C-BJ commented
There are actually other solutions, such as using other C standard libraries on Windows, but it might be more cumbersome

2023-05-14 10:58 UTC, kyouko-taiga commented
It is a very large effort to reimplement system calls directly in Val. It may be an interesting project in the long run, but in the short term I think it is more reasonable to reuse the C library.

2023-05-14 11:06 UTC, kyouko-taiga commented
Please keep in mind that, while Windows support would be _**awesome**_ to have, I think it is more important to focus on having a working language implementation that is easy to setup in the short run.

Most of our development is being done on Unix-like (specifically macOS) systems at the moment, so it's a reasonable choice to focus on the development experience on these systems in the short term. If we can afford to take shortcuts on Unix platforms, I'm ready to accept some technical debt. In this specific case, that means that I think Libc is out best bet.

I can see several possibilities to accommodate this choice on Windows. We can write C shims for Libc and link them to Val (similar to what the "support library" was doing) or we can get started with conditional compilation, pick a standard library on Windows, and write an adapter layer on Val. The latter option is probably more work, but it will also lead to a simpler setup for Windows user, probably.

I think this PR is not the best place to discuss these choices. That's why I suggest you open a community discussion.

2023-05-14 14:57 UTC, C-BJ commented
https://github.com/val-lang/val-lang.github.io/discussions/64

2023-05-14 21:35 UTC, dabrahams commented
One minor nit/note: we're already not using the Github CI matrix feature the way we should; the idea is to factor out common structure of build steps, and this one makes yet another copy of the workflow just for Windows.  I hope that if Windows gets sorted out we can fit it into a single set of matrix jobs.

2023-05-15 07:15 UTC, kyouko-taiga commented
> One minor nit/note: we're already not using the Github CI matrix feature the way we should; the idea is to factor out common structure of build steps, and this one makes yet another copy of the workflow just for Windows. I hope that if Windows gets sorted out we can fit it into a single set of matrix jobs.

Seems unlikely from what I understood has been going with our attempts to support Windows. Tooling around Swift and LLVM is different on Windows. The LibC problem also suggests further setup differences. IMO, if we really wanted to streamline a setup for all different OSes, we'd be better off using a tool that's made just for that and just call it from the GH workflow. Sadly, I don't have the time to work on that.

2023-05-15 13:01 UTC, dabrahams commented
There are ways to support differences; you can have conditionals on steps.  It's just programming.

2023-05-15 13:30 UTC, kyouko-taiga commented
It's not about whether or not you can program the workflow to work. It's about the benefits of doing it. Conditionals shine when there are only slight differences in the middle of relatively similar processes. Once you need to put a condition before most steps, the benefits of using a matrix become questionable.

GH workflows are cumbersome to develop and maintain because the fix/run/debug loop is painfully slow. Further, the efforts we put into them do not contribute to the configuration of the developer's environments. I think it will be more beneficial to factor out this work into a tool that we can reuse for CI as well as users and contributors.

2023-05-16 13:50 UTC, C-BJ commented
How long do you think it will take us to decide on that problem? @kyouko-taiga

2023-05-16 13:54 UTC, kyouko-taiga commented
A lot of moving pieces here. It is not an easy topic and I can't give it my full attention because I'm quite busy with the implementation of the generics. I will ask what other main contributors think about https://github.com/val-lang/val-lang.github.io/discussions/64 and we can plan something before the end of the week.

2023-05-26 13:19 UTC, C-BJ commented
Is there any progress? @kyouko-taiga 
I don't think it's really that hard to decide, you know

2023-05-26 13:57 UTC, kyouko-taiga commented
I think @dabrahams wanted to chime in.

2023-05-26 17:44 UTC, dabrahams commented
Sorry, what is the question, precisely?

2023-05-26 19:17 UTC, kyouko-taiga commented
The question is: what should we do in the short term w.r.t. Windows integration ?

IIRC you said you wanted to take the lead on this PR's review.

The latest problem is that Windows doesn't seem to support libc, which is currently a requirement of Val's standard library. There are ways to address this problem but AFAICT all of them require some non-trivial work, notably including the support of conditional compilation in Val. I expended on this topic [here](val-lang/val-lang.github.io#64).

My own two cents: as I am quite busy with other features, I personally don't have a lot of cycles to spend on this integration. Further, I am worried that the aforementioned problem is only one of a never ending list of Windows-specific issues that will keep slowing down development. Given the current state of the project, I would personally recommand to press pause on Windows and come back once we have a 1.0 release.

I would recommend Windows users to use either Docker or WSL. Thanks to Nick's contribution, the former should be really easy to setup.

2023-05-26 20:44 UTC, dabrahams commented
> The question is: what should we do in the short term w.r.t. Windows integration ?
>
> IIRC you said you wanted to take the lead on this PR's review.

I did? I wonder why.

> The latest problem is that Windows doesn't seem to support libc, which is currently a requirement of Val's standard library. There are ways to address this problem but AFAICT all of them require some non-trivial work, notably including the support of conditional compilation in Val. I expended on this topic [here](https://github.com/val-lang/val/pull/val-lang/val-lang.github.io#64).

<img width="1473" alt="image" src="https://github.com/val-lang/val/assets/44065/ec0214bb-5906-40f5-8a5f-037fd2215dca">

And there are no comments from you [here](https://github.com/val-lang/val-lang.github.io/discussions/64), so…?

> My own two cents: as I am quite busy with other features, I personally don't have a lot of cycles to spend on this integration. Further, I am worried that the aforementioned problem is only one of a never ending list of Windows-specific issues that will keep slowing down development. Given the current state of the project, I would personally recommand to press pause on Windows and come back once we have a 1.0 release.
> 
> I would recommend Windows users to use either Docker or WSL. Thanks to Nick's contribution, the former should be really easy to setup.

Seems to me that if we have an unsolved problem with libc, and we depend on it unconditionally, there's nothing to be done right now.  We don't have a working PR we can merge.  So to me it seems the obvious short term move is that Windows is unsupported until someone actually puts in the time to make our code pass the tests on Windows.  Maybe I'm missing something; the answer to the question seems too simple.  What other choice do we have?

2023-05-26 23:40 UTC, C-BJ commented
1. I have successfully passed Windows CI   
2. Windows is not without libc, but if you use Microsoft's libc, there will be very few functions that do not meet the C standard.

2023-05-27 00:03 UTC, dabrahams commented
The latest CI results don't show you passing anything, so I don't know what to make of your claim in 1.  If you can update this PR so it passes, I'll be happy to review the changes and see if I feel we can incorporate them.

2023-05-27 02:28 UTC, C-BJ commented
It pass the Windows CI at https://github.com/val-lang/val/pull/521/commits/a93c55cf210677c700e150e4cb2884c99d4fee99 and my subsequent commits were trying the conditional compilation method. All in all I've recommitted the code that passes Windows CI @dabrahams

2023-05-27 02:48 UTC, C-BJ commented
wait

2023-05-30 11:49 UTC, C-BJ commented
@dabrahams @kyouko-taiga

2023-05-30 22:28 UTC, kyouko-taiga commented
Unless I'm missing something, your PR is only passing on Windows but regresses on the other OSes. I understand you may be blocked by the inability to use conditional compilation in Val, but if that's the case, then my remarks stand and we should press pause on Windows integration.

I sympathize with the frustration that may be caused by my position, but please understand that any feature we merge is a burden we have to carry as the project progresses. It's one thing to get a green checkmark on Windows once. It's another to continuously support this OS as we're completing Val's implementation. It doesn't mean I don't care about Windows, only that it isn't a priority at this moment. Until it becomes one, there's always the option to run the compile through Docker or WSL.

If you are still dead set on supporting Windows natively, then perhaps you could try to work on the implementation of features blocking this PR, notably including conditional compilation.

2023-06-23 00:16 UTC, dabrahams commented
It seems to me that the portability issue could be solved pretty simply by reintroducing a C file in Val's core library that exposes the non-underscored symbols (the ones defined on unixes) to the windows build.  It would be conditionally empty using the preprocessor on all other OSes.

2023-07-14 06:57 UTC, C-BJ commented
> It seems to me that the portability issue could be solved pretty simply by reintroducing a C file in Val's core library that exposes the non-underscored symbols (the ones defined on unixes) to the windows build. It would be conditionally empty using the preprocessor on all other OSes.

I agree with this approach

2023-07-19 09:05 UTC, C-BJ commented
```error: couldn't build D:\a\val\val\.build\x86_64-unknown-windows-msvc\release\ValTests.build\ASTTests.swift.o because of missing inputs: D:\a\val\val\.build\plugins\outputs\val\ValTests\TestGeneratorPlugin\ValFileTests.swift```
Where is the `ValFileTests.swift`?

2023-07-19 22:47 UTC, kyouko-taiga commented
Might be a file produced by our test case generator @dabrahams ?

2023-07-20 03:28 UTC, dabrahams commented
> Might be a file produced by our test case generator @dabrahams ?

Correct.  It's possible you're running into [this](https://github.com/apple/swift-package-manager/issues/6595) SPM bug.

2023-07-20 08:38 UTC, C-BJ commented
But why does Linux run this test properly, and does it have anything to do with this code?
```
          swift test -c ${{ matrix.configuration }} ${{ matrix.host.test-options }} |
            tee testoutput.txt && (
              (grep -q "[.']EndToEndTests[/. ]test_" testoutput.txt && grep -q "[.']ValTests[/. ]test_" testoutput.txt) ||
              (echo "error: generated tests failed to run; see
              https://github.com/apple/swift-package-manager/issues/6595" && false) )
```

2023-07-20 14:22 UTC, dabrahams commented
@C-BJ That code exists to ensure that when the bug occurs, it fails loudly and we notice that the tests haven't run, because the only way we've seen the bug manifest before now was to silently skip tests.  If you read through the referenced bug report, you'll see that why it sometimes works and sometimes doesn't is a complete mystery to us.  Changing seemingly-irrelevant things like the name of the directory containing the project seem to affect it.

2023-07-20 15:31 UTC, C-BJ commented
what I can do for this? or try something? or disable this test generation for Windows?

2023-07-20 15:34 UTC, dabrahams commented
> Why does Linux run this test properly?
> 
> ![image](https://github.com/val-lang/val/assets/62678643/56c9350e-3993-4902-ab00-8aa4c2cf6f47)
> 
> only on xcode?

Theres no Xcode in linux. Read everything in the issue. Nobody understands this, so nobody can answer your question.

2023-07-27 14:15 UTC, C-BJ commented
Since we're again running into (suspected) Swift bugs preventing this PR from going forward, I decided to finish the rest of the code for Windows support in this PR, but not Enable Windows CI.

2023-07-27 14:45 UTC, kyouko-taiga commented
Sounds quite reasonable. If you managed to make everything work on your machine we might be able to claim unofficial and experimental Windows support on the README page, with a link to a an issue or community discussion to discuss troubleshooting.

2023-07-27 14:49 UTC, C-BJ commented
Yes, But I have a question, how do I make LibC.val use functions from my newly created LibC.h instead of functions from the C standard library?

2023-07-27 14:51 UTC, C-BJ commented
> 
It seems to me that the portability issue could be solved pretty simply by reintroducing a C file in Val's core library that exposes the non-underscored symbols (the ones defined on unixes) to the windows build. It would be conditionally empty using the preprocessor on all other OSes.

I can't make it very clear, but based on the methodology described above, I think you should be able to understand it.

2023-07-27 14:52 UTC, kyouko-taiga commented
I think you need to define a variant of `makeLinuxExecutable` in `ValCommand.swift` that will pass different flags to the linker.

2023-07-27 14:52 UTC, C-BJ commented
thanks, I will try it later

2023-07-28 03:24 UTC, C-BJ commented
Done

2023-07-28 04:22 UTC, C-BJ commented
I decided to keep CI to build Val on Windows, but not test it

2023-07-28 10:42 UTC, kyouko-taiga commented on .github/workflows/build-and-test.yml
> +#      run: swift test -c release
```suggestion
```
Probably better to avoid keeping commented lines. We already have commits with these if you want to look at how things were done in the future.

2023-07-28 10:43 UTC, kyouko-taiga commented on Examples/fortytwo.val
> +public fun main() -> Int {
Why changing this?

2023-07-28 10:46 UTC, kyouko-taiga commented on README.md
> +*Note to Windows users: although this project is **not** Unix-specific, and is expected to run properly on Windows, but due to an unknown bug in SPM, we are unable to ensure Val is running correctly
We should keep the note as it is. We' can't guarantee support until CI works. We can't claim it is "expected" to run properly until we can reliably test that it's true.

2023-07-28 10:47 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +  /// `binaryPath`, logging diagnostics to `log`.
Missing docs?

2023-07-28 10:47 UTC, kyouko-taiga commented on Sources/ValCommand/ValCommand.swift
> +    // Note: We use "clang" rather than "ld" so that to deal with the entry point of the program.
The comment is wrong. You're using `lld-link`.

2023-07-28 11:26 UTC, C-BJ commented on .github/workflows/build-and-test.yml
> +#      run: swift test -c release
OK

2023-07-28 11:27 UTC, C-BJ commented on Examples/fortytwo.val
> +public fun main() -> Int {
Oh, My bad

2023-07-28 11:27 UTC, C-BJ commented on README.md
> +*Note to Windows users: although this project is **not** Unix-specific, and is expected to run properly on Windows, but due to an unknown bug in SPM, we are unable to ensure Val is running correctly
I see

2023-07-28 11:28 UTC, C-BJ commented on Sources/ValCommand/ValCommand.swift
> +    // Note: We use "clang" rather than "ld" so that to deal with the entry point of the program.
I see

2023-07-28 11:46 UTC, C-BJ commented
I find that when the return value of main is 42 of type Int32, my command line will give a warning of abnormal termination of the program. Is this normal?

2023-07-28 11:48 UTC, C-BJ commented on Examples/fortytwo.val
> +public fun main() -> Int {
I wanted to change the type to test it, but I forgot to change it back

2023-07-29 10:27 UTC, kyouko-taiga commented
> I find that when the return value of main is number(except zero) of type Int32, my command line will give a warning of abnormal termination of the program. Is this normal?

Yes, normal return status is 0. Here we want to return another value to confirm that the program is doing something.

2023-07-29 12:09 UTC, C-BJ commented
but if the type of the return value is Int, my command line will not give a warning of abnormal termination of the program.

2023-07-29 12:10 UTC, C-BJ commented
btw, What else does this PR need to do? Can it be merged now?

2023-07-29 12:11 UTC, kyouko-taiga commented
> but if the type of the return value is Int, my command line will not give a warning of abnormal termination of the program.

That's a bug of the compiler.

2023-07-29 12:13 UTC, kyouko-taiga commented on README.md
> +*Note to Windows users: although this project is **not** Unix-specific, Windows support is not guaranteed due to the unexpected continuous integration failure (see https://github.com/val-lang/val/iss
Please don't change the message.

If you want to add links to your issue, refer to it in #252. Otherwise it will be harder to retrieve valuable information we already discussed.

2023-07-29 12:15 UTC, kyouko-taiga requested changes
Revert your change in the README and I think we should be fine. I'd like another pair of eyes on the PR before we merge it though.

2023-07-29 12:16 UTC, C-BJ commented on README.md
> +*Note to Windows users: although this project is **not** Unix-specific, Windows support is not guaranteed due to the unexpected continuous integration failure (see https://github.com/val-lang/val/iss
But the problem we discussed in #252 has been solved

2023-07-29 12:17 UTC, C-BJ commented on README.md
> +*Note to Windows users: although this project is **not** Unix-specific, Windows support is not guaranteed due to the unexpected continuous integration failure (see https://github.com/val-lang/val/iss
The issue with windows CI's flaky was resolved by retry

2023-07-29 12:18 UTC, kyouko-taiga commented on README.md
> +*Note to Windows users: although this project is **not** Unix-specific, Windows support is not guaranteed due to the unexpected continuous integration failure (see https://github.com/val-lang/val/iss
Not really. We're just trying a second time hoping the tests pass and assume two failures in a row are noteworthy.  CI is still flaky.

2023-07-29 12:18 UTC, C-BJ commented on README.md
> +*Note to Windows users: although this project is **not** Unix-specific, Windows support is not guaranteed due to the unexpected continuous integration failure (see https://github.com/val-lang/val/iss
The new issue is that Swift tests don't run properly on Windows

2023-07-29 12:19 UTC, C-BJ commented on README.md
> +*Note to Windows users: although this project is **not** Unix-specific, Windows support is not guaranteed due to the unexpected continuous integration failure (see https://github.com/val-lang/val/iss
OK

2023-07-29 12:19 UTC, kyouko-taiga commented on README.md
> +*Note to Windows users: although this project is **not** Unix-specific, Windows support is not guaranteed due to the unexpected continuous integration failure (see https://github.com/val-lang/val/iss
Then link both issues. But please keep the rest of the message as is.

2023-07-29 12:36 UTC, C-BJ commented
I suggest you change the title of #252. Because it can't even pass the test right now

2023-08-05 09:01 UTC, C-BJ commented
Is there any progress?

2023-08-06 00:15 UTC, dabrahams requested changes
Mostly this looks pretty awesome!  Please respond to my comments and I'm very inclined to merge this.

2023-08-06 00:15 UTC, dabrahams commented on Tests/EndToEndTests/ExecutionTests.swift
> +    #endif
```suggestion
    XCTAssert(result.standardOutput.last?.isNewline ?? false) // Allow for windows newline.
    XCTAssertEqual(result.standardOutput.dropLast(), "Hello, World!")
```

2023-08-06 00:15 UTC, dabrahams commented on Sources/ValCommand/ValCommand.swift
> +    try runCommandLine(find("lld-link"), arguments, diagnostics: &diagnostics)
```suggestion
    try runCommandLine(
      find("lld-link"), 
      ["-defaultlib:ValLibC", "-defaultlib:msvcrt", "-out:" + binaryPath] + objects.map(\.path),
      diagnostics: &diagnostics)
```

2023-08-07 09:13 UTC, C-BJ commented on Sources/GenerateValFileTests/GenerateValFileTests.swift
> +GenerateValFileTests.main()
https://forums.swift.org/t/main-in-a-single-swift-file/63079

2023-08-07 09:14 UTC, C-BJ commented on .github/workflows/build-and-test.yml
> +      if: steps.build.outcome != 'success'
I have set the id of the `Build (Release)` step to `build`

2023-08-07 09:19 UTC, C-BJ commented on .github/workflows/build-and-test.yml
> +      run: |
OK

2023-08-07 09:48 UTC, C-BJ commented on .github/workflows/build-and-test.yml
> +      run: |
![Uploading image.png…]()

2023-08-07 09:54 UTC, C-BJ commented
Format check has an unexpected error, but it has nothing to do with this PR

2023-08-07 09:54 UTC, C-BJ commented
Seems to be a network issue with the Github Action

2023-08-07 10:02 UTC, C-BJ commented
Well, it seems to be all right now

2023-08-07 10:16 UTC, C-BJ commented on .github/workflows/build-and-test.yml
> +      run: |
Oh, I think I misunderstood what you meant

2023-08-07 11:32 UTC, C-BJ commented on .github/workflows/build-and-test.yml
> +      run: |
Yes, If the first of the commands fails, the CI run will be shown as failing

2023-08-07 20:41 UTC, dabrahams commented
Thanks for all your work, @C-BJ !

2023-08-07 20:41 UTC, merged