`private` Access Modifier
val-lang/val pull request #651
Opened 2023-06-07 10:02 UTC by jlscheerer

This PR adds support for the `private` access modifier, as discussed with @kyouko-taiga.
It is possible to mark functions, method, binding, etc. declaration explicitly as `private`, e.g.,:
```
private fun my_private_function(_ a: let Int, _ b: let Int) -> Int { ... }
```
Furthermore, any declaration without access modifiers is treated implicitly as private.
We may consider a changing the `SourceRange` of the implicitly "generated" private access modifiers.

2023-06-07 10:04 UTC, kyouko-taiga commented on Sources/Core/AST/Decl/BindingDecl.swift
> +    // implicitly mark the binding as private
```suggestion
    // Declarations are private by default.
```

2023-06-07 10:06 UTC, kyouko-taiga commented on Sources/Core/AST/Decl/BindingDecl.swift
> +    self.accessModifier = accessModifier ?? SourceRepresentable(value: .private, range: site)
The constructor should take a non-optional property and let the parser synthesize it. That is how other properties are synthesized already.

2023-06-07 10:06 UTC, kyouko-taiga commented on Sources/Core/AST/Decl/ConformanceDecl.swift
> +    self.accessModifier = accessModifier ?? SourceRepresentable(value: .private, range: site)
Same remark about the non-optional constructor argument.

2023-06-07 10:06 UTC, kyouko-taiga commented on Sources/Core/AST/Decl/ExtensionDecl.swift
> +    self.accessModifier = accessModifier ?? SourceRepresentable(value: .private, range: site)
Same remark about the non-optional constructor argument.

2023-06-07 10:07 UTC, kyouko-taiga commented on Sources/Core/AST/Decl/InitializerDecl.swift
> +    self.accessModifier = accessModifier ?? SourceRepresentable(value: .private, range: site)
Same remark about the non-optional constructor argument.

2023-06-07 10:08 UTC, kyouko-taiga commented on Sources/FrontEnd/Parse/Parser.swift
> +        }
```suggestion
        else if let p = accessModifiers.first, p != access {
          state.diagnostics.insert(
            .error(
              inconsistentAccessModifiers: access,
              appearsAfterPreviousAccessModifier: p))
        }
```

We tend to avoid abbreviations in the code, or use single letter variables if the context allows.

2023-06-07 10:09 UTC, kyouko-taiga requested changes
Excellent work!

The only change that should be made is that modifiers should be synthesized by the parser rather than in the declarations' constructors.

2023-06-07 10:45 UTC, jlscheerer commented on Sources/Core/AST/Decl/BindingDecl.swift
> +    self.accessModifier = accessModifier ?? SourceRepresentable(value: .private, range: site)
Thank you very much for the feedback! Do you have any reference about how I can synthesize an object that is not an AST node (e.g., the AccessModifier)?

2023-06-07 12:54 UTC, kyouko-taiga commented on Sources/Core/AST/Decl/BindingDecl.swift
> +    self.accessModifier = accessModifier ?? SourceRepresentable(value: .private, range: site)
You can look at examples of synthesized declarations, like this [one](https://github.com/val-lang/val/blob/900601c03be0963c5fb21308d778df7c546fbb7e/Sources/FrontEnd/Parse/Parser.swift#L1057-L1086).

You can pick any range that makes sense for the synthesized site. For instance, we often use the first position of the declaration, like [here](https://github.com/val-lang/val/blob/900601c03be0963c5fb21308d778df7c546fbb7e/Sources/FrontEnd/Parse/Parser.swift#LL925C9-L925C88).

2023-06-07 19:57 UTC, jlscheerer commented
Thanks again for your review! I hope I have addressed all outstanding comments.

2023-06-08 11:23 UTC, kyouko-taiga commented on Sources/FrontEnd/Parse/Parser.swift
> +        // Catch incosistent access modifiers.
```suggestion
        // Catch inconsistent access modifiers.
```

2023-06-08 12:13 UTC, merged