Refactor fun decl
val-lang/val pull request #81
Opened 2022-11-10 04:35 UTC by kyouko-taiga

This PR splits the `FunDecl` into three types:
- `FunctionDecl`, which represents global, local, and member function declarations
- `MethodDecl`, which represents method bundle declarations
- `InitializerDecl`, which represents initializer declarations

Along with this change, the PR refactors a significant part of the parser so that AST invariants can be better enforced. Specifically, it uses continuation passing style to gather all information necessary to build a node before inserting it in the AST. As a result, declaration nodes no longer need to be modified after having being constructed, eliminating the need for most of the `incorporate` methods.

Finally, the PR refactors makes the API for generating diagnostics more uniform.

2022-11-12 23:15 UTC, dabrahams commented
If you want effective review, it helps to keep each PR to one primary code transformation.  In the narrative I see three different major transformations.  Please consider doing each one as a separate step.

2022-11-12 23:20 UTC, dabrahams commented on Sources/CLI/main.swift
> +  private var errorLabel  : String { "error: ".styled([.bold, .red]) }
```suggestion
  private var errorLabel : String { "error: ".styled([.bold, .red]) }
```

2022-11-13 00:40 UTC, kyouko-taiga commented
> please consider doing each one as a separate step

Point taken. Normally I would try to keep PR focused. The problem here was that refactoring `FunDecl` implied making heavy changes to the compiler.

2022-11-13 17:40 UTC, dabrahams requested changes
This PR is too big to review in a reasonable amount of time.  Please break it up into changes that make a single kind of code transformation and can be evaluated on their own.

2022-11-13 17:40 UTC, dabrahams commented on Sources/Compiler/AST/AST.swift
> +        let sourceFile = try SourceFile(contentsOf: sourceURL)
There's a suspicious amount of error handling mechanics here. Maybe we should talk this over

2022-11-13 17:40 UTC, dabrahams commented on Sources/Compiler/AST/AnyNode.swift
> -    case .funDecl                   : node = try container.decode(FunDecl.self)
Just a general concern that there's an awful lot of switches mapping between enum values and types.  Can we just use type values in place of the enum values?  Failing that, can you do all of this with a couple of dictionaries?

2022-11-13 17:40 UTC, dabrahams commented on Sources/Compiler/AST/Decl/AssociatedValueDecl.swift
> +  public let introducerRange: SourceRange?
```suggestion
  public let introducer: SourceRange?
```

2022-11-13 17:40 UTC, dabrahams commented on Sources/Compiler/AST/Decl/BindingDecl.swift
>    public init(
An aside: wondering if too much stuff is public.

2022-11-13 17:40 UTC, dabrahams commented on Sources/Compiler/AST/Decl/FunctionDecl.swift
> +    introducerRange: SourceRange?,
```suggestion
    introducer: SourceRange?,
```

2022-11-13 17:40 UTC, dabrahams commented on Sources/Compiler/AST/Decl/FunctionDecl.swift
> +  public func isWellFormed(in ast: AST) -> SuccessOrDiagnostics {
```suggestion
  public func validateForm(in ast: AST) -> SuccessOrDiagnostics {
```

2022-11-13 17:40 UTC, dabrahams commented on Sources/Compiler/AST/Decl/InitializerDecl.swift
> +  public let accessModifier: SourceRepresentable<AccessModifier>?
Isn't there a default access modifier?  Can't we synthesize it with an empty source range and avoid the optional?

2022-11-13 17:40 UTC, dabrahams commented on Sources/Compiler/AST/Decl/MethodDecl.swift
> +  /// The attributes of the declaration, if any.
```suggestion
  /// The attributes of the declaration.
```

2022-11-13 17:40 UTC, dabrahams commented on Sources/Compiler/AST/Decl/MethodDecl.swift
> +  public let introducerRange: SourceRange?
```suggestion
  /// The `fun` introducer, if any.
  public let introducer: SourceRange?
```

2022-11-13 17:40 UTC, dabrahams commented on Sources/Compiler/AST/Decl/NamespaceDecl.swift
> +  public func isWellFormed(in ast: AST) -> SuccessOrDiagnostics {
```suggestion
  public func validateForm(in ast: AST) -> SuccessOrDiagnostics {
```

or even

```suggestion
  public func checkForm(in ast: AST) -> SuccessOrDiagnostics {
```

2022-11-13 17:40 UTC, dabrahams commented on Sources/Compiler/AST/Decl/SubscriptImplDecl.swift
>    /// The declaration of the implicit receiver parameter, if any.
If it's implicit, how does it have a declaration?

2022-11-13 17:40 UTC, dabrahams commented on Sources/Compiler/AST/NodeIDs/NodeKind.swift
>       6 << 16 | decl.rawValue | genericScope.rawValue)
This kind of bit manipulation seems like it should be unnecessary and is probably at the very least premature optimization.

2022-11-13 17:47 UTC, kyouko-taiga commented on Sources/CLI/main.swift
> +      write("\(path):\(line):\(column): ".styled([.bold]))
I'm just replicating the aesthetics decisions of clang and swiftc.

2022-11-13 17:53 UTC, kyouko-taiga commented on Sources/Compiler/AST/AST+Invariants.swift
> +      ds.append(.diagnose(unexpectedAssociatedTypeDecl: self[NodeID(rawValue: decl.rawValue)]))
Maybe, but I couldn't find anything better.
- I tried using protocols but that is a poor solution because it forces you to have only one notional visit function per type.
- More promisingly, I tried using dispatch tables (i.e., dictionaries `[NodeKind: (AnyNodeID) -> Result]`) but it increased verbosity.

2022-11-13 17:56 UTC, kyouko-taiga commented on Sources/Compiler/AST/AST.swift
> +  public mutating func insert<T: Node>(_ n: T) throws -> NodeID<T> {
It is the single point where (syntactic) well-formedness has to be upheld, as the subtree rooted by `n` is immutable once it's been inserted. The convenience of automating the check in `insert(_:)` is extremely compelling.

2022-11-13 17:57 UTC, kyouko-taiga commented on Sources/Compiler/AST/AnyNode.swift
> -    case .funDecl                   : node = try container.decode(FunDecl.self)
I don't understand the remark nor the question.

2022-11-13 17:58 UTC, kyouko-taiga commented on Sources/Compiler/AST/Decl/AssociatedValueDecl.swift
> +  public let introducerRange: SourceRange?
This change would break consistency with other nodes, where `introducer` is a `SourceRepresentable<SomeIntroducerEnum>`

2022-11-13 17:59 UTC, kyouko-taiga commented on Sources/Compiler/AST/Decl/BindingDecl.swift
>    public init(
Might be too early to decide. I'm fairly certain AST nodes must be public,

2022-11-13 17:59 UTC, kyouko-taiga commented on Sources/Compiler/AST/Decl/FunctionDecl.swift
> +    introducerRange: SourceRange?,
Same answer as before.

2022-11-13 18:00 UTC, kyouko-taiga commented on Sources/Compiler/AST/Decl/InitializerDecl.swift
> +  public let accessModifier: SourceRepresentable<AccessModifier>?
Yes we could. That's a good idea.

2022-11-13 18:01 UTC, dabrahams commented on Sources/Compiler/AST/Decl/AssociatedValueDecl.swift
> +  public let introducerRange: SourceRange?
1. You could make it consistent by giving it an empty source range when it's implicit.
2. IMO it doesn't matter if it's consistent.  It's more important that the thing's name reflect its logical role.

2022-11-13 18:02 UTC, kyouko-taiga commented on Sources/Compiler/AST/Decl/SubscriptImplDecl.swift
>    /// The declaration of the implicit receiver parameter, if any.
It gets synthesized.

2022-11-13 18:03 UTC, kyouko-taiga commented on Sources/Compiler/AST/NodeIDs/NodeKind.swift
>       6 << 16 | decl.rawValue | genericScope.rawValue)
The code already exists, is not so hard to maintain, and I am not sure another form would make it obviously easier to read and/or maintain.

2022-11-13 18:04 UTC, kyouko-taiga commented on Sources/Compiler/AST/AST+Invariants.swift
> +import Utils
OK, will change after merge.

2022-11-13 18:10 UTC, dabrahams commented on Sources/Compiler/AST/AnyNode.swift
> -    case .funDecl                   : node = try container.decode(FunDecl.self)
Suppose `extension NodeID { typealias Kind = Node.Type }`?  Then couldn't you get rid of all these switch statements?

2022-11-13 18:12 UTC, kyouko-taiga commented
Sorry, I won't split the PR. I understand it is too big to get a proper review, but we need these changes to progress the AST refactoring process.

Many of your remarks relate to choices that have only been carried out. We can gradually improve on those once we have an AST that reflects the changes we made recently about the grammar (several changes on the syntax, plus the merge of TypeExpr and Expr).

I suggest you open issues so that we can keep track of the design choices you'd like to revisit.

2022-11-13 18:14 UTC, dabrahams commented on Sources/Compiler/AST/AST.swift
> +  public mutating func insert<T: Node>(_ n: T) throws -> NodeID<T> {
May I suggest this, then?

```
try program.insert(wellFormed: n)
```

2022-11-13 18:16 UTC, dabrahams commented on Sources/Compiler/AST/AST+Invariants.swift
> +      ds.append(.diagnose(unexpectedAssociatedTypeDecl: self[NodeID(rawValue: decl.rawValue)]))
I'm talking about lines almost exactly like the one I'm commenting on:

**ds.append(.diagnose(**unexpectedAssociatedTypeDecl: **self[NodeID(rawValue: decl.rawValue)]))**

The only really salient information in that line is the name of the error being diagnosed and it's buried in the middle.

2022-11-13 18:22 UTC, kyouko-taiga commented on Sources/Compiler/AST/AST+Invariants.swift
> +      ds.append(.diagnose(unexpectedAssociatedTypeDecl: self[NodeID(rawValue: decl.rawValue)]))
I tried to improve diagnostic reporting by transferring as much as the logic I could into the `diagnose` family of functions. I'm open to suggestions to make it even better.

`NodeID(rawValue otherID.rawValue)` is indeed boilerplate, but that's also the most efficient way to convert a node ID at call site. We could decide to use `NodeID(otherID)!` to make it shorter, at the cost of the forced unwrap.

2022-11-13 18:23 UTC, dabrahams commented
> Sorry, I won't split the PR. I understand it is too big to get a proper review, but we need these changes to progress on the AST refactoring process.

Sure, we need them (or some large subset of them).  But you can interactively rebase and organize your changes so even a large change makes a single kind of code transformation that can be quickly evaluated.  If you need some help doing that with Git, I'll be happy to show you how it's done.

> Many of your remarks relate to choices that have only been carried out. In a sense, you are reviewing the code I already wrote before that PR. 

Yes, those are just thoughts and meant to spark some discussion, not to meant to block acceptance of your change.

> We can gradually improve on those design choices once we have an AST that reflects the changes we made recently about the grammar (several changes on the syntax, plus the merge of TypeExpr and Expr).
> 
> I suggest you open issues so that we can keep track of the choices you'd like to revisit.

I'll try.

2022-11-13 18:27 UTC, kyouko-taiga commented on Sources/Compiler/AST/AST.swift
> +  public mutating func insert<T: Node>(_ n: T) throws -> NodeID<T> {
Looks good. I'll make the change.

2022-11-13 18:28 UTC, dabrahams commented
I'll have to wait to see which remarks you decide to address before I can tell which things should become issues.

2022-11-13 18:29 UTC, dabrahams commented on Sources/Compiler/AST/Decl/BindingDecl.swift
>    public init(
But do they need to be publicly initializable?

2022-11-13 18:30 UTC, dabrahams commented on Sources/Compiler/AST/NodeIDs/NodeKind.swift
>       6 << 16 | decl.rawValue | genericScope.rawValue)
IMO `typealias NodeKind = Node.Type` would probably make all of this unnecessary.

2022-11-13 18:32 UTC, kyouko-taiga commented on Sources/Compiler/AST/Decl/BindingDecl.swift
>    public init(
Yes, because I think we'll eventually expose Val compiler as a library that lets you programmatically create ASTs.

2022-11-13 18:34 UTC, kyouko-taiga commented on Sources/Compiler/AST/NodeIDs/NodeKind.swift
>       6 << 16 | decl.rawValue | genericScope.rawValue)
Unfortunately no.

I originally designed it that way. Then I ended up writing a lot of code that was testing for nodes that belong to the same syntactic category (e.g., all lexical scopes, all type declarations, etc.). So I defined an additional bit to implement the `<=` operator.

2022-11-13 18:38 UTC, kyouko-taiga commented on Sources/Compiler/AST/Decl/AssociatedValueDecl.swift
> +  public let introducerRange: SourceRange?
That's a good topic for an issue.

2022-11-13 18:41 UTC, kyouko-taiga commented on Sources/Compiler/AST/Decl/FunctionDecl.swift
> +  public func isWellFormed(in ast: AST) -> SuccessOrDiagnostics {
Will change.

2022-11-13 18:44 UTC, kyouko-taiga commented on Sources/Compiler/AST/AnyNode.swift
> -    case .funDecl                   : node = try container.decode(FunDecl.self)
Hmm, you're probably right. Good topic for an issue.

2022-11-13 18:46 UTC, dabrahams commented on Sources/Compiler/AST/Decl/SubscriptImplDecl.swift
>    /// The declaration of the implicit receiver parameter, if any.
```suggestion
  /// The synthesized declaration of the implicit receiver parameter, if any.
```

2022-11-13 18:47 UTC, kyouko-taiga commented
I made some of the suggested changes. I think other suggestions could be discussed as issues (I already opened a couple).

2022-11-13 18:53 UTC, dabrahams commented on Sources/Compiler/AST/NodeIDs/NodeKind.swift
>       6 << 16 | decl.rawValue | genericScope.rawValue)
What `<=` should mean on a node kind is non-obvious to me.  What's wrong with `kind is Scope.Type` or `kind as? Scope.Type` for testing categories?

2022-11-13 18:57 UTC, dabrahams commented on Sources/Compiler/AST/AST+Invariants.swift
> +      ds.append(.diagnose(unexpectedAssociatedTypeDecl: self[NodeID(rawValue: decl.rawValue)]))
I think you're missing my point.  There's gotta be a way to refactor so you're just writing something like

```
unexpectedAssociatedTypeDecl(decl)
```

instead of all that repetitive stuff I've bolded.

2022-11-13 19:04 UTC, kyouko-taiga commented on Sources/Compiler/AST/NodeIDs/NodeKind.swift
>       6 << 16 | decl.rawValue | genericScope.rawValue)
The kind of `ProductTypeDecl` is not `LexicalScope`, it is `ProductTypeDecl`. So you cannot test whether `someTypeErasedID` (which might be a product type) is a lexical scope using that approach.

If you use the meta type of the referred node as its kind, then AFAICT there's no obvious way to type `AnyNodeID.kind`.

2022-11-13 19:05 UTC, kyouko-taiga commented on Sources/Compiler/AST/NodeIDs/NodeKind.swift
>       6 << 16 | decl.rawValue | genericScope.rawValue)
Operator `<=` is implementing a sort of subtyping check.

```swift
if decl.kind <= .lexicalScope {
  // decl is an ID of any type that is a lexical scope.
}
```

2022-11-13 19:08 UTC, kyouko-taiga commented on Sources/Compiler/AST/AST+Invariants.swift
> +      ds.append(.diagnose(unexpectedAssociatedTypeDecl: self[NodeID(rawValue: decl.rawValue)]))
I think you already suggested that approach, and I'm not sure I like it.

`diagnose(unexpectedAssociatedTypeDecl:)` might be called in different types, not only `AST`. So to make your call work we'll have to define `unexpectedAssociatedTypeDecl(_:)` in `AST` and any other type that may produce this diagnostic.

That, I believe, is also boilerplate that will have to be maintained every time we want to change the API of the diagnostic generator.

2022-11-13 23:10 UTC, dabrahams commented on Sources/Compiler/AST/AST+Invariants.swift
> +      ds.append(.diagnose(unexpectedAssociatedTypeDecl: self[NodeID(rawValue: decl.rawValue)]))
Still missing my point.  I'm not attached to that call form.  I mean you should increase the salient information density.

2022-11-13 23:51 UTC, dabrahams commented on Sources/Compiler/AST/NodeIDs/NodeKind.swift
>       6 << 16 | decl.rawValue | genericScope.rawValue)
I don't follow.  `ProductTypeDecl` does conform to `LexicalScope`.  If you have a `someTypeErasedID` storing `ProductTypeDecl.self` as its `.kind` of static type `Node.Type`, you can write `someTypeErasedID.kind is LexicalScope.Type` and get your answer.  What am I missing?

2022-11-14 00:20 UTC, kyouko-taiga commented on Sources/Compiler/AST/NodeIDs/NodeKind.swift
>       6 << 16 | decl.rawValue | genericScope.rawValue)
OK, didn't know you could use the `is` operator that way. That's a great idea then. Can you make the change?

2022-11-14 00:21 UTC, kyouko-taiga commented on Sources/Compiler/AST/AST+Invariants.swift
> +      ds.append(.diagnose(unexpectedAssociatedTypeDecl: self[NodeID(rawValue: decl.rawValue)]))
If you show me how, I am interested. Otherwise, I think the current design is the best I could do so far.

2022-11-14 19:06 UTC, merged