Immutable ast contd
val-lang/val pull request #83
Opened 2022-11-11 20:41 UTC by kyouko-taiga

2022-11-12 23:11 UTC, dabrahams reviewed
This PR has a lot of changes that seem to be unrelated to making the AST immutable, which makes review difficult.

2022-11-12 23:13 UTC, dabrahams commented
I think part of the problem is that the base branch of the PR ought to have been refactor-FunDecl rather than main.

2022-11-12 23:50 UTC, dabrahams commented on Sources/Compiler/AST/AST+Invariants.swift
> +    var ds: [Diagnostic] = []
The name `ds` is a weird grammatical mix. I read it as “Ds,” i.e. a collection of D objects, whatever D is supposed to mean.  What is it about being a collection that warrants giving it special status and injecting type information into its name?

```suggestion
    var report: [Diagnostic] = []
```

or even 

```suggestion
    var log: [Diagnostic] = []
```

2022-11-13 18:05 UTC, kyouko-taiga commented on Sources/Compiler/AST/AST+Invariants.swift
> +    var ds: [Diagnostic] = []
OK, reasonable request. I'll create an issue.

2022-11-13 18:07 UTC, kyouko-taiga commented
Ah, my mistake. It was supposed to be.

2022-11-14 23:27 UTC, dabrahams requested changes
Most of the comments are in the parts before IR.  Reviewing got tiring at some point and I was unable to usefully continue.  I hope what I've written is of some use.

2022-11-14 23:27 UTC, dabrahams commented on Sources/Compiler/AST/Expr/SequenceExpr.swift
> +  /// Creates an instance with the given properties.
See, you haven't told me the significance of `tail`, so I can't know what it means to create an instance with the given `tail` property.

2022-11-14 23:27 UTC, dabrahams commented on Sources/Compiler/AST/Expr/SequenceExpr.swift
> +  public func isWellFormed(in ast: AST) -> SuccessOrDiagnostics {
```suggestion
  public func wellFormedness(in ast: AST) -> SuccessOrDiagnostics {
```
Anything but an `is` prefix for a non-`Bool` returning function.

2022-11-14 23:27 UTC, dabrahams commented on Sources/Compiler/AST/Expr/SequenceExpr.swift
> +    var ds: [Diagnostic] = []
We have a better name for `ds` now, right?

2022-11-14 23:27 UTC, dabrahams commented on Sources/Compiler/AST/Name.swift
> +  /// Returns a textual descriptions of `labels`.
```suggestion
  /// Returns a textual description of `labels`.
```

2022-11-14 23:27 UTC, dabrahams commented on Sources/Compiler/AST/Name.swift
> +    labels.reduce(into: "", { (s, l) in s += (l ?? "_") + ":" })
When building strings, you will get better performance and your code will come out a lot clearer if you lazily map things into strings and then `.join` them, than if you try to do reduction with append.

Even when the strings to be joined are dynamic, it will be much much clearer to map them and then `.join`, and we'll probably never notice a difference in performance.

You can also reduce noise in the code that does `message.write("...\n")` over and over by `message.append("...")` and then using `.join(separator: "\n")`

2022-11-14 23:27 UTC, dabrahams commented on Sources/Compiler/AST/PassingConvention.swift
> +  /// Creates a convnetion matching the given receiver effect.
```suggestion
  /// Creates a convention matching the given receiver effect.
```

2022-11-14 23:27 UTC, dabrahams commented on Sources/Compiler/AST/PassingConvention.swift
> +  /// Creates a convention matching the given remote type capability.
What does it mean to create a convention matching a remote type capability?   A doc comment should give me enough information to write a test.

Also, please don't use "the given _\<type rewritten in english\>_."  It's a silly convention used by DevPubs that takes up valuable words that could be used to give real salient information.

```suggestion
  /// Creates an instance matching `capability`.
```

But then use the space you've won to write something meaningful :-)

2022-11-14 23:27 UTC, dabrahams commented on Sources/Compiler/AST/Name.swift
> +  public static func describe(labels: [String?]) -> String {
You sure this should be public?

2022-11-14 23:27 UTC, dabrahams commented on Sources/Compiler/IR/Emitter.swift
> +    let explicitCaptures = program.ast[declID].explicitCaptures
It's a bit hard to tell what's going on here; I get the feeling shorter local variable names might make it easier, and I also get the sense the function is getting a bit long…which might be helped by shorter names.  Not sure, so do with this remark what you will.

2022-11-14 23:27 UTC, dabrahams commented on Sources/Compiler/IR/Emitter.swift
> +    switch expr {
I'm not really able to evaluate most of this code.  It looks plausible, but I don't know the codebase well enough to really tell for sure.  If it's well-covered by tests in this PR, then I think we can be pretty confident.  If not, please write some more tests :-)

2022-11-15 14:10 UTC, kyouko-taiga commented on Sources/Compiler/AST/Expr/FoldedSequenceExpr.swift
> +  mutating func append(callee: Callee, right: AnyExprID) {
I think we need to discuss this. I didn't understand anything.

2022-11-15 14:15 UTC, kyouko-taiga commented on Sources/Compiler/IR/Emitter.swift
> +    let explicitCaptures = program.ast[declID].explicitCaptures
This part needs work. But I think we should rethink how captures work in general. That would have the potential to simplify IR lowering.

2022-11-15 14:18 UTC, kyouko-taiga commented on Sources/Compiler/AST/Name.swift
> +  public static func describe(labels: [String?]) -> String {
I really don't see the harm in exposing a helper function that implements boilerplate. But we can make it internal if you think it's necessary.

IMO it doesn't hurt local reasoning. Nothing is mutating and from the docs it is clear that the function only serves getting human-readably descriptions.

2022-11-15 14:22 UTC, kyouko-taiga commented on Sources/Compiler/AST/Expr/FoldedSequenceExpr.swift
> +  public typealias Callee = (expr: NodeID<NameExpr>, precedence: PrecedenceGroup?)
The operator is the callee of a binary operation. But your suggestion makes sense.

2022-11-15 14:24 UTC, kyouko-taiga commented on Sources/Compiler/AST/Expr/SequenceExpr.swift
> +    public var `operator`: NodeID<NameExpr>
`operatorName` repeats the information that's already in the type `NameExpr`. I'm trying to apply your advice here.

2022-11-15 14:24 UTC, kyouko-taiga commented on Sources/Compiler/AST/Expr/SequenceExpr.swift
> +  /// The first operand of the expression.
Yep, will add to the docs.

2022-11-15 15:10 UTC, kyouko-taiga commented on Sources/Compiler/AST/Name.swift
> +    labels.reduce(into: "", { (s, l) in s += (l ?? "_") + ":" })
Not entirely convinced `labels.map({ "\($0 ?? "_"):" }).joined()` is easier to read, but OK.

2022-11-15 15:21 UTC, kyouko-taiga commented on Sources/Compiler/AST/Name.swift
> +    labels.reduce(into: "", { (s, l) in s += (l ?? "_") + ":" })
Because I was intrigued I ran a micro benchmark. FWIW, `reduce` is 25% faster than `map`.

2022-11-15 15:30 UTC, kyouko-taiga commented on Sources/Compiler/AST/PassingConvention.swift
> +  /// Creates a convention matching the given remote type capability.
I think I am getting unconvinced that all functions must be 100% understandable to the point of someone being able to write unit tests by their single-line documentation. That is a fine principle, really, but here I don't think any comment can be clearer than the 6-lines body.

I'll be honest. Have to scratch my head trying to come up with a good comment for this kind of function feels like a disincentive to refactor the boilerplate that it removed elsewhere.

2022-11-15 16:01 UTC, dabrahams commented on Sources/Compiler/AST/Name.swift
> +  public static func describe(labels: [String?]) -> String {
The less you expose publicly, the clearer the abstraction you intend clients to see becomes for the reader.

2022-11-15 16:02 UTC, kyouko-taiga commented on Sources/Compiler/AST/Name.swift
> +    labels.reduce(into: "", { (s, l) in s += (l ?? "_") + ":" })
lazy map is much, much worse, about 10x.

2022-11-15 16:07 UTC, kyouko-taiga commented on Sources/Compiler/AST/Name.swift
> +  public static func describe(labels: [String?]) -> String {
I don't disagree with this principle. I'm saying that I genuinely do not believe making this function internal makes the abstraction any clearer.

2022-11-15 16:11 UTC, dabrahams commented on Sources/Compiler/AST/Expr/SequenceExpr.swift
> +    public var `operator`: NodeID<NameExpr>
I appreciate that, thank you.  It doesn't work 100% of the time, so one needs to be judicious.  In this case, I'm just asking you to think it through one more time.   Also, if you take `Name` out of the name, maybe ought to leave it in the comment, _if_ there's any useful distinction at all between an operator and and its name at this level.

2022-11-15 16:12 UTC, dabrahams commented on Sources/Compiler/AST/Name.swift
> +  public static func describe(labels: [String?]) -> String {
:shrug: It's—at _least_—the difference between a smaller API and a larger one.  The smaller one is always easier to understand.

2022-11-15 16:16 UTC, dabrahams commented on Sources/Compiler/AST/Expr/FoldedSequenceExpr.swift
> +  /// A leaf node representing some expression.
```suggestion
  /// An expression that is not, at the top level, an operator application.
```

Or something.  What you wrote is obvious from the declaration.  Use the opportunity provided by the comment to say something more.

2022-11-15 16:17 UTC, kyouko-taiga commented on Sources/Compiler/AST/Expr/SequenceExpr.swift
> +    public var `operator`: NodeID<NameExpr>
Can you have a look at the updated file and tell me if you still feel uncomfortable with the names of those properties? IMO `operator` is the name that best reflects the role of this property in the sub-tree represented by `TailElement`.

2022-11-15 16:22 UTC, kyouko-taiga commented on Sources/Compiler/AST/Expr/FoldedSequenceExpr.swift
> +  /// A leaf node representing some expression.
Does the precision adds anything useful to the reader?

What you wrote is wrong because `AnyExprID` can represent, well any expression. That includes another `SequenceExpr`, which doesn't violate well-formedness if it was obtained from`a * (b + c)`. Further `!a` is also an operator application that certainly can be a leaf node.

I feel like adding qualification to exclude this cases will just make the comment heavier.

2022-11-15 16:22 UTC, dabrahams commented on Sources/Compiler/AST/Expr/FoldedSequenceExpr.swift
> +  case parent(operator: Operator, left: FoldedSequenceExpr, right: FoldedSequenceExpr)
```suggestion
  /// The application of an operator to its `left` and `right` operands.
  case operator(Operator, left: FoldedSequenceExpr, right: FoldedSequenceExpr)
```

perhaps?

2022-11-15 16:24 UTC, kyouko-taiga commented on Sources/Compiler/AST/Name.swift
> +  public static func describe(labels: [String?]) -> String {
OK. Can you suggest the change?

2022-11-15 16:44 UTC, dabrahams commented on Sources/Compiler/AST/PassingConvention.swift
> +  /// Creates a convention matching the given remote type capability.
Don't view scratching your head to come up with a good comment as a burden; it's an opportunity. It is part of the process of understanding your own code and the problem you're solving, and eventually arriving at the right API.  The comment is for the consumer of the function who doesn't see the implementation, not the person who wrote it.  I don't know what a “remote type capability” is.  Should there even be a type for it distinct from `PassingConvention`?

2022-11-15 16:45 UTC, dabrahams commented on Sources/Compiler/AST/Name.swift
> +  public static func describe(labels: [String?]) -> String {
```suggestion
  private static func describe(labels: [String?]) -> String {
```

2022-11-15 16:49 UTC, dabrahams commented on Sources/Compiler/AST/Name.swift
> +    labels.reduce(into: "", { (s, l) in s += (l ?? "_") + ":" })
Huh, we should do better in Val! Can you post a gist link to your microbenchmark?
My argument is about clarity, but if the performance difference is significant I withdraw the suggestion.

2022-11-15 17:33 UTC, kyouko-taiga commented on Sources/Compiler/AST/Name.swift
> +  public static func describe(labels: [String?]) -> String {
Can't be `private`, must be internal. I'll make the change.

2022-11-15 22:12 UTC, dabrahams commented on Sources/Compiler/AST/Expr/FoldedSequenceExpr.swift
> +  /// A leaf node representing some expression.
> Does the precision adds anything useful to the reader?

Absolutely, yes.

> What you wrote is wrong

Which goes to show that I don't understand the abstraction being documented here.

2022-11-15 22:24 UTC, kyouko-taiga commented on Sources/Compiler/AST/Name.swift
> +    labels.reduce(into: "", { (s, l) in s += (l ?? "_") + ":" })
Here's the microbenchmark: https://gist.github.com/kyouko-taiga/91223b1c76ff4af8e2f19f4dce72e65f

2022-11-16 01:58 UTC, kyouko-taiga commented on Sources/Compiler/AST/PassingConvention.swift
> +  /// Creates a convention matching the given remote type capability.
Perhaps, although I am not sure what should be done for `yielded`. The current code predates the latest iteration of remote types.

I'll keep the status quo until remote types are better specified.

2022-11-16 02:00 UTC, kyouko-taiga commented
I opened an issue for the suggestions that I thought were out of scope for the PR.

2022-11-16 02:01 UTC, merged